<?php

$breadcrumbs[] = array(
    'url' =>  BASE_URL.'/auth/empresas/index',
    'title' => 'Empresas',
    'text' => 'Empresas'
);

$head = 'Empresas';

$newButton = array(
    'title' => 'Nova Empresa',
    'href' => BASE_URL.'/auth/empresas/save',
    'text' => 'Nova Empresa'
);



$addIcon[] = array(
		'url' => BASE_URL.'/auth/empresas/save',
		'title' => 'Editar',
		'classButton' => 'glyphicon glyphicon-pencil',
		'classHref' => 'edit',
);
$addIcon[] = array(
		'url' =>BASE_URL. '/auth/empresas/delete',
		'title' => 'Excluir',
		'classButton' => 'glyphicon glyphicon-trash',
		'classHref' => 'remove',
);

$tableInformation = array(
    array('index' => 'id',
        'format' => '',
        'descricao' => 'Id',
    ),
    array('index' => 'nome_empresa',
        'format' => 'nameFormatter',
        'descricao' => 'Nome da empresa',
    ),
    array('index' => 'operate',
        'format' => 'operateFormatter',
        'descricao' => 'Operações',
        'events' => 'operateEvents',
        ));

echo $this->partial('partials/datatable/template.phtml', array('breadcrumbs' => $breadcrumbs,
    'head' => $head,
    'newButton' => $newButton,
    'addIcon' => $addIcon,
    'tableInformation' => $tableInformation
));
?>