
<?php
echo"<div id='tableUm'>";
echo $this->formRow($form->get('tableI'));
echo"</div>";
 
echo"<div id='navigator-table'>";
echo $this->formRow($form->get('AdicionarTodos'));
echo $this->formRow($form->get('Adicionar'));
echo $this->formRow($form->get('Remover'));
echo $this->formRow($form->get('RemoverTodos'));
echo"</div>";//navigator

echo"<div id='tableDois'>"; 
echo $this->formRow($form->get('tableII'));
echo"</div>";
?>
<!-- Vai setar os Id's no options dos MultiSelects -->
<script type="text/javascript">
    setID('tableI', 'tableII');
</script>
