<?php

$breadcrumbs[] = array(
    'url' => BASE_URL . '/auth//programasperfis/index',
    'title' => 'Vincular Programa Perfil',
    'text' => 'Vincular Programa Perfil',
);

$newButton = array(
    'title' => 'Vincular Programa Perfil',
    'href' => BASE_URL . '/auth/programasperfis/save',
    'text' => 'Vincular Programa Perfil',
);

$addIcon[] = array(
    'url' => BASE_URL . '/auth/programasperfis/delete',
    'title' => 'Excluir',
    'classButton' => 'glyphicon glyphicon-trash',
    'classHref' => 'remove',
);
$tableInformation = array(
    array('index' => 'id',
        'format' => '',
        'descricao' => 'Id',
    ),
    array('index' => 'desc_programa',
        'format' => '',
        'descricao' => 'Programa',
    ),
    array('index' => 'desc_perfil',
        'format' => '',
        'descricao' => 'Perfil',
    ),
    array('index' => 'operate',
        'format' => 'operateFormatter',
        'descricao' => 'Operações',
        'events' => 'operateEvents'
    ),
);
echo $this->partial('/partials/datatable/template.phtml', array(
    'breadcrumbs' => $breadcrumbs,
    'newButton' => $newButton,
    'addIcon' => $addIcon,
    'tableInformation' => $tableInformation,
));
?>