<?php
/**
 * Controlador Pessoas
 * @data 17-04-2013
 * @category Application 
 * @package Controller 
 * @author  Willian Gustavo Mendo <willianmendo@unochapeco.edu.br>
 */
$breadcrumbs = array();
$breadcrumbs[0]['url'] = BASE_URL.'/auth/logs';
$breadcrumbs[0]['title'] = 'Logs';
$breadcrumbs[0]['text'] = 'Logs';
$head = 'Logs de atividades';
$tableIndex = array();
$i = 0;
$partialElements[] = array(
		'name' => 'start',
		'information' => 'Data de início da pesquisa ',
		'label' => $this->formLabel($form->get('start')->setLabelAttributes(array('for' => 'start'))),
		'input' => $this->formInput($form->get('start')),
);
$partialElements[] = array(
		'name' => 'end',
		'information' => 'Data de término da pesquisa',
		'label' => $this->formLabel($form->get('end')->setLabelAttributes(array('for' => 'end'))),
		'input' => $this->formInput($form->get('end')),
);
$buttonPesquisar= array(
		'title' => 'Filtrar Logs',
		'href' => BASE_URL.'/auth/logs',
		'text' => 'Filtrar',
);
foreach ($json[0] as $chave => $j) {
    $index[$i] = $chave;
    $i++;
}
$tableInformation = array(
    array('index' => $index[0],
        'format' => '',
        'descricao' => 'Id',
    ),
	array('index' => $index[6],
		'format' => '',
		'descricao' => 'Usuário',
	),
	array('index' => $index[1],
        'format' => 'dateFormatter',
        'descricao' => 'Data',
    ),
    array('index' => $index[2],
        'format' => '',
        'descricao' => 'Hora',
    ),
    array('index' => $index[3],
        'format' => '',
        'descricao' => 'Ação',
    ),
    array('index' => $index[4],
        'format' => '',
        'descricao' => 'Controlador',
    ),
    array('index' => $index[5],
        'format' => '',
        'descricao' => 'Módulo',
    ),
);
$help = 'Logs de atividades dos usuários';
$range = 'Intervalo de tempo de busca:';
echo $this->partial('/partials/datatable/templateLogs.phtml', array(
	'breadcrumbs' => $breadcrumbs,
    'head' => $head,
    'tableInformation' => $tableInformation,
	'buttonPesquisar' => $buttonPesquisar,
	'partialElements' => $partialElements,
	'help' => $help,
	'range' => $range,
	'form' => $form,
));
?>