<?php
 
$breadcrumbs[] = array(
    'url' => BASE_URL.'/auth/acao/index',
    'title' => 'Acçoes',
    'text' => 'Ações'
);
$head = 'Ações';

$newButton = array(
    'title' => 'Nova Ação',
    'href' => BASE_URL.'/auth/acao/save',
    'text' => 'Nova Ação'
);

$tableInformation = array(
    array('index' => 'id',
        'format' => '',
        'descricao' => 'Id'
    ), array('index' => 'desc_acao',
        'format' => 'nameFormatter',
        'descricao' => 'Descrição da ação',
    ), array('index' => 'acao_url',
        'format' => '',
        'descricao' => 'Action Url'
    ), array('index' => 'desc_programa',
        'format' => '',
        'descricao' => 'Programa'
    ), array('index' => 'controller_programa',
        'format' => '',
        'descricao' => 'Controller'
    ), array('index' => 'nome_filial',
        'format' => '',
        'descricao' => 'Filial'
    ), array('index' => 'desc_modulo_filial',
        'format' => '',
        'descricao' => 'Modulo'
    ), array('index' => 'operate',
        'format' => 'operateFormatter',
        'descricao' => 'Operações',
        'events' => 'operateEvents'
    ),
);

$addIcon[] = array(
		'url' =>BASE_URL.'/auth/acao/save',
		'title' => 'Editar',
		'classButton' => 'glyphicon glyphicon-pencil',
		'classHref' => 'edit',
);
$addIcon[] = array(
		'url' => BASE_URL.'/auth/acao/delete',
		'title' => 'Excluir',
		'classButton' => 'glyphicon glyphicon-trash',
		'classHref' => 'remove',
);


echo $this->partial('/partials/datatable/template.phtml', array('breadcrumbs' => $breadcrumbs,
    'head' => $head,
    'newButton' => $newButton,
    'tableInformation' => $tableInformation,
    'addIcon' => $addIcon,
));
?>