<?php

$breadcrumbs[] = array(
    'url' => BASE_URL.'/auth/acao/index',
    'title' => 'Ação',
    'text' => 'Ação'
);
$breadcrumbs[] = array(
    'url' => BASE_URL.'/auth/acao/save',
    'title' => 'Nova Ação',
    'text' => 'Nova Ação'
);
 
$partialElements[] = array(
    'name' => 'id_filial',
    'label' => $this->formLabel($form->get('id_filial')->setLabelAttributes(array('for' => 'Filial'))),
    'input' => $this->formSelect($form->get('id_filial'))
);
$partialElements[] = array(
    'name' => 'id_programa',
    'label' => $this->formLabel($form->get('id_programa')->setLabelAttributes(array('for' => 'Programa'))),
    'input' => $this->formSelect($form->get('id_programa')),
);

$partialElements[] = array(
    'name' => 'desc_acao',
    'label' => $this->formLabel($form->get('desc_acao')->setLabelAttributes(array('for' => 'Descrição Acão'))),
    'input' => $this->formInput($form->get('desc_acao')),
);

$partialElements[] = array(
    'name' => 'acao_url',
    'label' => $this->formLabel($form->get('acao_url')->setLabelAttributes(array('for' => 'Url Ação'))),
    'input' => $this->formInput($form->get('acao_url')),
);

$partialElements[] = array(
    'name' => 'id',
    'input' => $this->formHidden($form->get('id')),
);

$help = 'Nessa tela você pode cadastrar uma ação para um programa pertencente a uma filial, campos com * são obrigatórios.';

echo $this->partial('/partials/form/template.phtml', array(
    'breadcrumbs' => $breadcrumbs,
    'partialElements' => $partialElements,
    'form' => $form,
    'help' => $help));
?>  

<script type="text/javascript">
function reload(){ 
    setTimeout(function () {
            $('#id_programa').selectpicker('refresh');
        }, 800);
}    
</script>
