	<!--===================================================-->
	<div class="cls-content">
		<div class="cls-content-sm panel">
					<div class="panel">
					<div class="panel-heading">
							<h3 class="panel-title">SELECIONE UMA FILIAL</h3>
						</div>
						<div class="panel-body">
							<div class="list-group list-group-striped">
							<?php
								foreach ($filial as $f) {
							?>
							<a class="list-group-item" href="<?php echo BASE_URL; ?>/auth/selecionar-perfil/selecionar-perfil/id/<?php echo $f['id'] ?>"><?php echo $f['nome_filial']; ?></a>
							<?php } ?>
							</div>
						</div>
			</div>
		</div>

		<div class="pad-ver">
			<a href="<?php echo BASE_URL; ?>/auth/auth/logout" class="btn-link mar-rgt">Sair</a>
		</div>
	</div>

	<!--===================================================-->

        <label class="msg">
            <?php
            if ($this->session()->offsetGet('error')) {
                echo $this->session()->offsetGet('error');
                $this->session()->offsetUnset('error');
            }
            ?>
        </label>