<style>
    .list-group{
        margin-top: 20px !important ;
    }
    .panel{
        margin-top: 0px;
    }
    .cls-content-sm {
        color : #ffffff !important;
    }
</style>

	<!--===================================================-->
	<div class="cls-content">
		<div class="cls-content-sm">
<!--					<div class="panel">-->
					<div class="panel-heading">
							<h3 class="panel-title" style="font-size: 1.4em; font-weight: bold">SELECIONE UM PERFIL</h3>
						</div>
						<div class="panel-body">
<!--							<div class="list-group list-group-striped">-->
							<?php
								foreach ($perfil as $p) {
							?>
							<a class="list-group-item" href="<?php echo BASE_URL; ?>/auth/selecionar-perfil/selecionar-programa/id/<?php echo $p['id'] ?>"><?php echo $p['desc_perfil']; ?></a>
							<?php } ?>
<!--							</div>-->
						</div>
<!--			</div>-->
		</div>

		<div class="pad-ver">
			<a href="<?php echo BASE_URL; ?>/auth/auth/logout" class="btn-link mar-rgt">Sair</a>
		</div>
	</div>
        <label class="msg">
            <?php
            if ($this->session()->offsetGet('error')) {
                echo $this->session()->offsetGet('error');
                $this->session()->offsetUnset('error');
            }
            ?>
        </label>