<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else {
                    if (isset($modal)) {
                        ?>
                        <li><a href="#" title="Opções" onclick="mostrarModals();"><?php echo $modal; ?></a></li>
                    <?php } ?>
                    <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
                    <?php
                }
            }
            ?>
        </ol>
    <?php } ?>

<?php $id_processo = $this->session()->offsetGet('processo');?>
<script type="text/javascript">
    function mostrarModals() {
        var processo;
        var etapa;
        $JQuery(function () {
            $.ajax({
                type: 'POST',
                url: '<?php echo BASE_URL ?>/main/processo-apuracao/etapa-processo',
                data: {'id': <?php echo $id_processo ?>},
                dataType: 'JSON',
                async: false,
                success: function (d) {
                    etapas(d);
                }
            });
            $('#dialog-new').modal('toggle');
            $JQuery("#titulo-modal").replaceWith('<h4 class="modal-title" id="titulo-modal"><b>Etapas do processo:</b> <?= $modal ?></h4>');
        });
    }
    ;
    function etapas(d) {
        $JQuery('#importacao').removeClass();
        $JQuery('#importacao').addClass(d.importacao.classe);
        $JQuery('#importaxml').removeClass();
        $JQuery('#importaxml').addClass(d.nfe.classe);
        if (d.nfe.block !== '') {
            $JQuery('#importaxml').css('pointer-events', 'none');
        } else {
            $JQuery('#importaxml').css('pointer-events', '');
        }
        $JQuery('#importacte').removeClass();
        $JQuery('#importacte').addClass(d.cte.classe);
        if (d.cte.block !== '') {
            $JQuery('#importacte').css('pointer-events', '');
            $JQuery('#importacte').css('pointer-events', 'none');
        } else {
            $JQuery('#importacte').css('pointer-events', '');
        }
        $JQuery('#conciliacao').removeClass();
        $JQuery('#conciliacao').addClass(d.conciliacao.classe);
        if (d.conciliacao.block !== '') {
            $JQuery('#conciliacao').css('pointer-events', 'none');
        } else {
            $JQuery('#concilaicao').css('pointer-events', '');
        }
        $JQuery('#regras').removeClass();
        $JQuery('#regras').addClass(d.regras.classe);
        if (d.regras.block !== '') {
            $JQuery('#regras').css('pointer-events', 'none');
        } else {
            $JQuery('#regras').css('pointer-events', '');
        }
        $JQuery('#apuracaosped').removeClass();
        $JQuery('#apuracaosped').addClass(d.apuracao.classe);
        if (d.apuracao.block !== '') {
            $JQuery('#apuracao').css('pointer-events', 'none');
        } else {
            $JQuery('#apuracao').css('pointer-events', '');
        }
        $JQuery('#exportar').removeClass();
        $JQuery('#exportar').addClass(d.exportacao.classe);
        if (d.exportacao.block !== '') {
            $JQuery('#exportar').css('pointer-events', 'none');
        } else {
            $JQuery('#exportar').css('pointer-events', '');
        }
    }

    function importar() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importar/save/id/<?php echo $id_processo ?>');
    }
    ;
    function importaxml() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarxml/index/id/<?php echo $id_processo ?>');
    }
    ;
    function importacte() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarcte/index/id/<?php echo $id_processo ?>');
    }
    ;
    function apuracao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/apuracao/index/id/<?php echo $id_processo ?>');
    }
    ;
    function encerrar() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/encerramento/id/<?php echo $id_processo ?>');
        }
    }
    ;
    function exportar() {
        window.location.assign('<?= BASE_URL; ?>' + '/exportacao/exportar-xls/index/id/<?php echo $id_processo ?>');
    }
    ;
    function regras() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/regrasprocesso/index/id/<?php echo $id_processo ?>');
    }
    ;
    function remover() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/delete/id/<?php echo $id_processo ?>');
        }
    }
    ;
    function conciliacao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/conciliacao/index/id/<?php echo $id_processo ?>');
    }
    ;
</script>
