
<style>
    #fecharImp{
        float: right;
        margin-top: -50px;
        margin-right: 15px;
        height: auto;
    }
</style>

<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                    <?php
                } else {
                    if (isset($modal)) {
                        ?>
                        <li><a href="#" title="Opções" onclick="mostrarModals();"><?php echo $modal; ?></a></li>
                    <?php } ?>
                    <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
                    <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<div id="page-content">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->help; ?></h3>
            <?php if ($this->fecharImp === 1) { ?>
                <div id='fecharImp' class='form-group'>
                    <input id="demo-sw-sz-md" type="checkbox"  checked>
                    <span id="demo-sw-checkstate-field" class="label label-info"></span>
                </div>
            <?php } ?>
        </div>
        <div class="panel-body">
            <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
            <!--===================================================-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">
            <!--===================================================-->
            <!-- END OF PAGE CONTENT -->
            <!-- BLOCK STYLED FORM FORM  -->
            <!--===================================================-->
            <?php
            echo $this->form()->openTag($this->form);
            $messageError = $this->form->getMessages();
            ?>
            <div id="append" class="panel-body">
                <?php
                $cont = 0;
                foreach ($this->partialElements as $chave => $element) {
                    if (isset($element['id_div'])) {
                        $idDiv = 'id="' . $element['id_div'] . '"';
                    } else {
                        $idDiv = '';
                    }
                    if ($element['name'] != 'perfis') {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                        ?>
                        <?php if ($cont == 0) { ?>
                            <div class="row">
                            <div class="col-sm-6">
                                <div <?php echo $idDiv; ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (isset($element['label'])) {
                                        echo $element['label'];
                                    }
                                    if (!isset($element['type'])) {
                                        echo $element['input'];
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>
                                        <span class="btn btn-default btn-file">
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>
                                </div>
                            </div>
                            <?php
                            $cont = 1;
                        } else {
                            ?>
                            <div class="col-sm-6">
                                <div <?php echo $idDiv; ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (isset($element['label'])) {
                                        echo $element['label'];
                                    }
                                    if (!isset($element['type'])) {
                                        echo $element['input'];
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>
                                        <span class="btn btn-default btn-file">
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>
                                </div>
                            </div>
                            </div>
                            <?php
                            $cont = 0;
                        }
                        ?>

                        <?php
                    }
                }
                if(isset($importar)){
                    ?><div class="col-sm-6">
                        <div id="esconder" class="form-group " style="display: block;">
                            <label for="importar[0][]"></label>
                            <br>
                                <span id="importar0" class="btn btn-default btn-file">
                                    <label for="importar[0][]">Selecione os arquivos</label>
                                    <input id="importar[0][]" class="pull-left btn btn-default btn-file" type="file" value="Selecione os arquivos" multiple="multiple" placeholder="Selecine os arquivos" name="importar[0][]">
                                </span>
                            <span class="info clearfix"> </span>
                        </div>
                    </div>

                    <div class="row">

                        <div class="eq-height" style=" margin-right: 25px;">
                            <div class="eq-height" style="margin-right: 25px;">
                                <div class="col-md-12 col-lg-12" id="div_tabs">
                                        <div class="tab-base">
                                            <ul class="nav nav-tabs">
                                                <li id="01" class="active"><a data-toggle="tab" href="#demo-lft-tab-1">Janeiro</a></li>
                                                <li id="02"><a data-toggle="tab" href="#demo-lft-tab-2">Fevereiro</a></li>
                                                <li id="03"><a data-toggle="tab" href="#demo-lft-tab-3">Março</a></li>
                                                <li id="04"><a data-toggle="tab" href="#demo-lft-tab-4">Abril</a></li>
                                                <li id="05"><a data-toggle="tab" href="#demo-lft-tab-5">Maio</a></li>
                                                <li id="06"><a data-toggle="tab" href="#demo-lft-tab-6">Junho</a></li>
                                                <li id="07"><a data-toggle="tab" href="#demo-lft-tab-7">Julho</a></li>
                                                <li id="08"><a data-toggle="tab" href="#demo-lft-tab-8">Agosto</a></li>
                                                <li id="09"><a data-toggle="tab" href="#demo-lft-tab-9">Setembro</a></li>
                                                <li id="010"><a data-toggle="tab" href="#demo-lft-tab-10">Outubro</a></li>
                                                <li id="011"><a data-toggle="tab" href="#demo-lft-tab-11">Novembro</a></li>
                                                <li id="012"><a data-toggle="tab" href="#demo-lft-tab-12">Dezembro</a></li>
                                            </ul>
                                            <div class="tab-content" style='width: 96%;'>
                                                <?php
                                                for ($i = 1; $i <= 12; $i++) {
                                                    $class = $i == 1 ? "tab-pane fade active in" : "tab-pane fade";
                                                    ?>
                                                    <div id="demo-lft-tab-<?= $i ?>" class="<?= $class ?>">
                                                        <div class="panel">
                                                            <div class="col-sm-6">
                                                                <div id="esconder<?= $i ?>" class="form-group " style="display: block;">
                                                                    <label for="importar[<?= $i ?>][]"></label>
                                                                    <br>
                                                                <span class="btn btn-default btn-file">
                                                                    <label for="importar[<?= $i ?>][]">Selecione os arquivos</label>
                                                                    <input id="importar[<?= $i ?>][]" class="pull-left btn btn-default btn-file" type="file" value="Selecione os arquivos" multiple="multiple" placeholder="Selecine os arquivos" name="importar[<?= $i ?>][]">
                                                                </span>
                                                                    <span class="info clearfix"> </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <?php
                                                }
                                                ?>
                                            </div>
                                        </div>

                                </div>
                            </div>
                        </div>
                    </div>
                <?php }
                if ($cont == 1)
                    echo '</div>';
                echo '</div>';
                if (isset($checkbox)) {
                    foreach ($checkbox as $chave => $element) {
                        ?>
                        <?php if (!isset($element['class'])) { ?>
                            <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                            <div class="checkbox">
                                <!-- INLINE CHECKBOXES -->
                                <!--===================================================-->
                                <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                    <label class="form-checkbox form-icon active">
                                        <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id']; ?>" value="<?php echo $chaves; ?>" type="checkbox"><?php echo $elements; ?>
                                    </label>
                                    <!--===================================================-->
                                <?php } ?>
                                <?php
                                if (isset($messageError[$element['name']])) {
                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                }
                                ?>
                            </div>

                        <?php } else { ?>
                            <div id="switch" class="form-group">
                                <input id="demo-sw-sz-lg" type="checkbox" checked>
                                <span id="demo-sw-checkstate-field" class="label label-info">Servidor</span>
                            </div>
                        <?php } ?>
                        <?php
                    }
                }
                ?>
                <div class="panel-footer text-right">
                    <?php $submitbutton = isset($this->btnSubmit) ? "$this->btnSubmit" : "Salvar" ?>
                    <button id="submitbutton" type="submit" class="btn btn-primary"><?= $submitbutton ?></button>
                    <?php
                    if (array_key_exists('cancelar', $this->form->getElements()))
                        echo $this->formButton($this->form->get('cancelar'));
                    ?>
                </div>
                <?php echo $this->form()->closeTag($this->form); ?>
                <!--===================================================-->
                <!-- END OF BLOCK STYLED FORM FORM  -->

                <!--====================================================-->
                <!-- FILTERS -->

                <div id="overlay">
                    <?php
                    if(isset($this->filter)){?>
                        <div id="filter">
                            <?php foreach($this->filter as $f) { ?>
                                <label class="form-checkbox form-icon active form-text">
                                    <input name="<?php echo $f['name']; ?>[]" value="<?php echo $f['value']; ?>"
                                           type="checkbox" onchange="<?php echo $f['funcao']; ?>"<?php if($f['check']) echo "checked"; ?>><?php echo $f['desc']; ?>
                                </label>

                            <?php } ?>
                        </div>
                    <?php } ?>




                    <!--====================================================-->
                    <!-- END OF FILTERS -->

                    <div class="bootstrap-table">
                        <?php if (isset($this->newButton)) { ?>
                            <div class="panel-footer text-left">
                                <a class="btn btn-lg btn-primary" href='<?php echo $this->newButton['href'] ?>'><?php echo $this->newButton['text'] ?></a>
                            </div>
                        <?php } ?>
                        <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-sort-name="id" data-sort-order="desc" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1">
                            <thead>
                            <tr>
                                <?php
                                foreach ($this->tableInformation as $th) {
                                    if ($th['index'] == 'checkbox') {
                                        ?>
                                        <th data-align="center" data-sortable="false" data-checkbox="true"></th><?php } else { ?>
                                        <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php
                                        if (isset($th['events'])) {
                                            echo $th['events'];
                                        }
                                        ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
                                        <?php
                                    }
                                }
                                ?>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <script>
        $JQuery(function() {
            $JQuery('[name="refresh"]').click(function() {
                var aux = '<?php echo $this->breadcrumbs[0]['url'] . '/ajax/1'; ?>';
                $('#demo-table').bootstrapTable('refresh', {url: aux});
            });
        });
        function nameFormatter(value, row) {
            if (value)
                return '<a href="<?php echo $this->addIcon[0]['url']; ?>/id/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
            return '-';
        }
        function nameFormatterTxt(value, row) {
            if (value)
                return '<a href="<?php echo $this->addIcon[0]['url']; ?>/txt/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
            return '-';
        }
        function operateFormatter(value, row, index) {
            return [
                <?php foreach ($this->addIcon as $item) { ?>
                '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" title="<?php echo $item['title']; ?>">',
                '<i class="<?php echo $item['classButton']; ?>"></i>',
                '</a>&nbsp;&nbsp;&nbsp;',
                <?php } ?>
            ].join('');
        }
        function dateHourFormatter(value, row) {
            var aux = value;
            if (aux !== null){
                var auxData = aux['date'].split(" ");
                var a = auxData[0].split("-");
                var b = auxData[1].split(":");
                var data = a[2] + '-' + a[1] + '-' + a[0] + ' ' + b[0] + ':' + b[1];
                console.log(data);
                return '<span><i class="fa fa-clock-o"></i> ' + data + '</span>';
            } else {
                return '<span><i></i> </span>';
            }
        }

        window.operateEvents = {
            <?php
            foreach ($this->addIcon as $item) {
                if ($item['classHref'] == 'remove') {
                    ?>
            'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
                if (confirm('Deseja deletar este registro?') == true){
                    window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                    console.log(value, row, index);
                }
            },
            <?php } else { ?>
            'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
                window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                console.log(value, row, index);
            },
            <?php } ?>
            <?php } ?>
        };
        <?php $id_processo = $this->session()->offsetGet('processo'); ?>
        <?php if ($id_processo >= 1) { ?>
        function mostrarModals(){

            var id;
            var processo;
            var etapa;
            $JQuery(function () {
                $.ajax({
                    type: 'POST',
                    url: '<?php echo BASE_URL ?>/main/processo-apuracao/etapa-processo',
                    data: {'id': <?php echo $id_processo ?>},
                    dataType: 'JSON',
                    async: false,
                    success: function (d) {
                        etapas(d);
                    }
                });
                $('#dialog-new').modal('toggle');
                $JQuery("#titulo-modal").replaceWith('<h4 class="modal-title" id="titulo-modal"><b>Etapas do processo:</b> <?= $modal ?></h4>');
            });
        };
        <?php } ?>
        function etapas(d) {
            $JQuery('#importacao').removeClass();
            $JQuery('#importacao').addClass(d.importacao.classe);
            $JQuery('#importaxml').removeClass();
            $JQuery('#importaxml').addClass(d.nfe.classe);
            if (d.nfe.block !== '') {
                $JQuery('#importaxml').css('pointer-events', 'none');
            } else {
                $JQuery('#importaxml').css('pointer-events', '');
            }
            $JQuery('#importacte').removeClass();
            $JQuery('#importacte').addClass(d.cte.classe);
            if (d.cte.block !== '') {
                $JQuery('#importacte').css('pointer-events', '');
                $JQuery('#importacte').css('pointer-events', 'none');
            } else {
                $JQuery('#importacte').css('pointer-events', '');
            }
            $JQuery('#conciliacao').removeClass();
            $JQuery('#conciliacao').addClass(d.conciliacao.classe);
            if (d.conciliacao.block !== '') {
                $JQuery('#conciliacao').css('pointer-events', 'none');
            } else {
                $JQuery('#concilaicao').css('pointer-events', '');
            }
            $JQuery('#regras').removeClass();
            $JQuery('#regras').addClass(d.regras.classe);
            if (d.regras.block !== '') {
                $JQuery('#regras').css('pointer-events', 'none');
            } else {
                $JQuery('#regras').css('pointer-events', '');
            }
            $JQuery('#apuracaosped').removeClass();
            $JQuery('#apuracaosped').addClass(d.apuracao.classe);
            if (d.apuracao.block !== '') {
                $JQuery('#apuracao').css('pointer-events', 'none');
            } else {
                $JQuery('#apuracao').css('pointer-events', '');
            }
            $JQuery('#exportar').removeClass();
            $JQuery('#exportar').addClass(d.exportacao.classe);
            if (d.exportacao.block !== '') {
                $JQuery('#exportar').css('pointer-events', 'none');
            } else {
                $JQuery('#exportar').css('pointer-events', '');
            }
        }

        function importar() {
            window.location.assign('<?= BASE_URL; ?>' + '/importacao/importar/save/id/<?php echo $id_processo ?>');
        };
        function importaxml() {
            window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarxml/index/id/<?php echo $id_processo ?>');
        };
        function importacte() {
            window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarcte/index/id/<?php echo $id_processo ?>');
        };
        function apuracao() {
            window.location.assign('<?= BASE_URL; ?>' + '/main/apuracao/index/id/<?php echo $id_processo ?>');
        };
        function encerrar() {
            if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
                window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/encerramento/id/<?php echo $id_processo ?>');
            }
        };
        function exportar() {
            window.location.assign('<?= BASE_URL; ?>' + '/exportacao/exportar-xls/export/id/<?php echo $id_processo ?>');
        };
        function regras() {
            window.location.assign('<?= BASE_URL; ?>' + '/main/regrasprocesso/index/id/<?php echo $id_processo ?>');
        };
        function remover() {
            if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
                window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/delete/id/<?php echo $id_processo ?>');
            }
        };
        function conciliacao() {
            window.location.assign('<?= BASE_URL; ?>' + '/main/conciliacao/index/id/<?php echo $id_processo ?>');
        };
    </script>