<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
if ($this->breadcrumbs) {
    $keys = array_keys($this->breadcrumbs);
    $endKey = end($keys);
    ?>
    <ol class="breadcrumb">
        <li>Você está aqui: </li>
        <?php
        foreach ($this->breadcrumbs as $chave => $breadcrumb) {
            if ($breadcrumb['url'] == '#')
                $urlBreadcrumb = '#';
            else
                $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
            ?>
            <?php if ($endKey != $chave) { ?>
                <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } else { ?>
                <li class="active"><?php echo $breadcrumb['text']; ?></li>
                <?php
            }
        }
        ?>
    </ol>
<?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<!-- ##### HEAD DA PAGINA #####-->
<div id="page-title">
    <h1 class="page-header text-overflow"><?php echo $this->head; ?>
</div>
<!-- ##### FIM DA HEAD #####-->
<!--===================================================-->
<!-- PERMITE O FUNCIONAMENTO DO DATEPICKER -->
<div id="demo-range-def" style="display: none;"></div>
<div id="demo-range-step" style="display: none;"></div>
<div id="demo-range-ver1" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver2" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver3" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver4" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver5" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-vpips" class="demo-pips demo-range-ver pips" style="display: none;"></div>
<div id="demo-range-drg" style="display: none;"></div>
<div id="demo-range-fxt" style="display: none;"></div>
<div id="demo-range-com" style="display: none;"></div>
<div id="demo-range-hpips" class="demo-pips pips" style="display: none;"></div>
<!-- FIM -->
<!--===================================================-->
<div id="page-content">
    <div class="panel">
    	<div class="panel-heading">
					<h3 class="panel-title"><?php echo $this->help; ?></h3>
		</div>
        <div class="panel-body">
            <div class="bootstrap-table">
            <div class="panel-footer text-left">
            	<?php echo $this->form()->openTag($this->form);?>
					<p class="text-thin mar-btm"><?php echo $this->range; ?></p>
							<!--BOOTSTRAP DATEPICKER : RANGE-->
							<!--===================================================-->
							<div id="demo-dp-component">
								<div class="input-group date">
									<span class="input-group-addon"> <?php echo $this->partialElements[0]['label'];?> </span>
									<?php echo $this->partialElements[0]['input'];?>
									<span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
								</div>
								<div class="input-group date">
									<span class="input-group-addon"><?php echo $this->partialElements[1]['label'];?></span>
									<?php echo $this->partialElements[1]['input'];?>
									<span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
								</div>
							</div>
							<!--===================================================-->
							<div style="display: none;">
								<input id="demo-sw-checkstate" type="checkbox" checked/>
							<span id="demo-sw-checkstate-field" class="label label-info"></span>
							</div>
				
				<button id="submitbutton" type="submit" class="btn btn-primary"><?php echo $this->buttonPesquisar['text'] ?></button>
                <?php echo $this->form()->closeTag($this->form); ?>
                </div>
                <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-sort-name="id" data-sort-order="desc" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1">
                    <thead>
                        <tr>   
                            <?php foreach ($this->tableInformation as $th) { ?>    
                                <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php if (isset($th['events'])) {
                                echo $th['events'];
                            	} ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
							<?php
							}
							?>
                        </tr>
                    </thead>
                </table>
                <div class="panel-footer text-left">
            	<?php echo $this->form()->openTag($this->form);?>
					<p class="text-thin mar-btm"><?php echo $this->range; ?></p>
							<!--BOOTSTRAP DATEPICKER : RANGE-->
							<!--===================================================-->
							<div id="demo-dp-component">
								<div class="input-group date">
									<span class="input-group-addon"> <?php echo $this->partialElements[0]['label'];?> </span>
									<?php echo $this->partialElements[0]['input'];?>
									<span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
								</div>
								<div class="input-group date">
									<span class="input-group-addon"><?php echo $this->partialElements[1]['label'];?></span>
									<?php echo $this->partialElements[1]['input'];?>
									<span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
								</div>
							</div>
							<!--===================================================-->
							<div style="display: none;">
								<input id="demo-sw-checkstate" type="checkbox" checked/>
							<span id="demo-sw-checkstate-field" class="label label-info"></span>
							</div>
				
				<button id="submitbutton" type="submit" class="btn btn-primary"><?php echo $this->buttonPesquisar['text'] ?></button>
                <?php echo $this->form()->closeTag($this->form); ?>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>