<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else { ?>
                    <li class="active"><?php echo $breadcrumb['text']; ?></li>
                    <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<!-- ##### HEAD DA PAGINA #####-->
<?php if (isset($this->head)) { ?>
    <div id="page-title">
        <h1 class="page-header text-overflow"><?php echo $this->head; ?>
    </div>
<?php } ?>
<!-- ##### FIM DA HEAD #####-->

<div id="page-content">        
    <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
    <!--===================================================-->
    <input id="demo-sw-checkstate" type="hidden">
    <input id="demo-sw-checkstate-field"  type="hidden">

    <?php
    echo $this->form()->openTag($this->form);
    $messageError = $this->form->getMessages();
    ?>                                            
    <div class="row">
        <div class="eq-height">
            <div class="col-md-12 col-lg-12">
                <div class="tab-base">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#demo-lft-tab-1">Dados gerais</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-2">Valores</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-3">Emitente</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-4">Tomador</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-5">Remetente</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-6">Destinatário</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-7">Carga</a></li>
                    </ul>
                    <div class="tab-content">
                        <?php
                        for ($i = 1; $i <= 7; $i++) {
                            switch ($i) {
                                case 1: $num = "demo-lft-tab-1";
                                    $grupo = "dados_nota";
                                    break;
                                case 2: $num = "demo-lft-tab-2";
                                    $grupo = "valores";
                                    break;
                                case 3: $num = "demo-lft-tab-3";
                                    $grupo = "emitente";
                                    break;
                                case 4: $num = "demo-lft-tab-4";
                                    $grupo = "tomador";
                                    break;
                                case 5: $num = "demo-lft-tab-5";
                                    $grupo = "remetente";
                                    break;
                                case 6: $num = "demo-lft-tab-6";
                                    $grupo = "destinatario";
                                    break;
                                case 7: $num = "demo-lft-tab-7";
                                    $grupo = "carga";
                                    break;
                            }
                            $class = $i == 1 ? "tab-pane fade active in" : "tab-pane fade";
                            ?>
                            <div id="<?= $num ?>" class="<?= $class ?>">
                                <div class="panel-body">
                                    <table class="table table-striped">
                                        <tbody>
                                            <?php
                                            foreach ($this->partialElements as $chave => $element) {
                                                if ($element['grupo'] == $grupo) {
                                                    echo "<tr>";
                                                    if (isset($element['label'])) {
                                                        echo "<td>" . $element['label'] . "</td>";
                                                    }
                                                    if (isset($element['input'])) {
                                                        echo "<td>" . $element['input'] . "</td>";
                                                    }
                                                    echo "</tr>";
                                                }
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                        <div class="panel-footer text-right">
                            <?php
                            echo $this->formButton($this->form->get('cancelar'));
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>                     
    <?php echo $this->form()->closeTag($this->form); ?>
</div>

<script>
    window.operateEvents = {
<?php
foreach ($this->addIcon as $item) {
    if ($item['classHref'] == 'remove') {
        ?>
            'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            if (confirm('Deseja deletar este registro?') == true){
            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                    console.log(value, row, index);
            }
            },
    <?php } else { ?>
            'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                    console.log(value, row, index);
            },
    <?php } ?>
<?php } ?>
    };
</script>
