<div class="row">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>Categorias</h5>
            </div>
            <div class="panel-body">
                <a href="<?= BASE_URL ?>/produtos/categorias/save" class="btn btn-default">
                    Nova Categoria
                </a>
                <table class="table table-hover table-bordered table-striped table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Descrição</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($categorias as $categoria) { ?>
                        <tr>
                            <td><?= $categoria->getId(); ?></td>
                            <td><?= $categoria->getDescCategoria(); ?></td>
                            <td>
                                <a href="<?= BASE_URL?>/produtos/categorias/save/id/<?= $categoria->getId()?>">ED</a>
                                <a href="<?= BASE_URL?>/produtos/categorias/delete/id/<?= $categoria->getId()?>">EX</a>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>

</div>