<?php

$breadcrumbs[] = array(
    'url' => BASE_URL.'/auth/filiais/index',
    'title' => 'Filial',
    'text' => 'Filial'
);
$breadcrumbs[] = array(
    'url' => BASE_URL.'/auth/filiais/save',
    'title' => 'Nova Filial',
    'text' => 'Nova Filial'
);

$partialElements[] = array(
    'name' => 'nome_filial',
    'label' => $this->formLabel($form->get('nome_filial')->setLabelAttributes(array('for' => 'nome_filial'))),
    'input' => $this->formInput($form->get('nome_filial'))
);
$partialElements[] = array(
    'name' => 'desc_modulo_filail',
    'label' => $this->formLabel($form->get('desc_modulo_filial')->setLabelAttributes(array('for' => 'desc_modulo_filial'))),
    'input' => $this->formInput($form->get('desc_modulo_filial')),
);
$partialElements[] = array(
    'name' => 'desc_exibi_filial',
    'label' => $this->formLabel($form->get('desc_exibi_filial')->setLabelAttributes(array('for' => 'Descrição da Filial'))),
    'input' => $this->formInput($form->get('desc_exibi_filial')),
);
$partialElements[] = array(
    'name' => 'id_empresa',
    'label' => $this->formLabel($form->get('id_empresa')->setLabelAttributes(array('for' => 'id_empresa'))),
    'input' => $this->formSelect($form->get('id_empresa'))
);
$partialElements[] = array(
    'name' => 'url_img_filial',
    'input' => $this->formInput($form->get('url_img_filial')),
    'label' =>$this->formLabel($form->get('url_img_filial')->setLabelAttributes(array('for' => 'url_img_filial'))),
    'type' => 'file',
);
$partialElements[] = array(
    'name' => 'id',
    'input' => $this->formHidden($form->get('id'))
);

$help = 'Nessa tela é cadastrada uma nova filial, campos com * são obrigatórios.';


echo $this->partial('partials/form/template.phtml', array(
      'breadcrumbs' => $breadcrumbs, 
      'titlePage' => 'Nova Filial', 
      'partialElements' => $partialElements,
      'form' => $form,
      'help' => $help));
?>  
