<?php echo $this->doctype(); ?>
<?php $programa = $this->session()->offsetGet('programas');
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sistema de Apuração Fiscal - DIMO Soluções'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/themes/base/jquery-ui.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet('/jqGrid/css/ui.jqgrid.css')
                ->appendStylesheet('/css/jquery.ui.datepicker.css')
                ->appendStylesheet('/plugins/ui.multiselect.css');
        ?>
      
          <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.js')
                ->prependFile($this->basePath() . '/js/main.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/jquery.cookie.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'text/javascript')
                ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                ->appendFile($this->basePath() .'/jqGrid/js/i18n/grid.locale-en.js', 'text/javascript')
                ->appendFile($this->basePath() .'/plugins/ui.multiselect.js', 'text/javascript')
                ->appendFile($this->basePath() .'/jqGrid/js/jquery.jqGrid.min.js', 'text/javascript');
        
        ;
        ?>
        
        <style type="text/css">
            .page-header{
                margin-right: 100px;
                margin-top: -30px;
            }
            #menuFavero{
                width: 220px;
                float: left;
                border: 1px solid gray;
            }
            body {
                background-image: none;
                padding-top: 40px;
                padding-bottom: 40px;
            }
            #conteudo{
                margin-left: 5px;
                float: left;
                width: 80%;
            }
            .page-header a{
                font-size: 18px;
                float:right;

            }
        </style>
        <script type="text/javascript">

        </script>
    </head>
    <body>

        <div class="page-header">
            <h1><img src="<?php echo $this->basePath('img/favero.png') ?>"> Favero & Associados <small>Sistema Interno</small></h1>
            <a href="/auth/auth/logout">SAIR </a>
        </div>
        <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
            <div class="success_msg">
                <?php
                foreach ($this->flashMessenger()->getSuccessMessages() as $msg) {
                    echo $msg;
                }
                ?>
            </div>
        <?php } ?>
        <!-- Msg Error -->

        <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
            <div class="error_msg">
                <?php
                foreach ($this->flashMessenger()->getErrorMessages() as $msg) {
                    echo $msg;
                }
                ?>
            </div>
        <?php } ?>

        <!-- Msg Warning -->   

        <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
            <div class="warning_msg">
                <?php
                foreach ($this->flashMessenger()->getInfoMessages() as $msg) {
                    echo $msg;
                }
                ?>
            </div>
        <?php } ?>
        <div>
            <div id="menuFavero">
                <ul class="nav nav-pills nav-stacked">
                    <?php foreach ($programa as $p) { ?>
                        <li><a href="<?php echo BASE_URL; ?>/auth/selecionar-perfil/carregar-sessao/id/<?php echo $p['id'] ?>"><?php echo $p['desc_programa']; ?></a></li>
                    <?php } ?>
                </ul>
            </div>
            <div id="conteudo">
                <?php echo $this->content; ?>
            </div>
        </div>

        <?php echo $this->inlineScript() ?>

        <hr>
        <footer>
            <p>&copy; 2012 - <?php echo date('Y') ?> by DIMO Soluções Ltda. </p>
        </footer>

    </body>
</html>
