<?php

$breadcrumbs[] = array(
    'url' => BASE_URL.'/auth/programas/index',
    'title' => 'Programas',
    'text' => 'Programas'
);

$newButton = array(
    'title' => 'Novo Programa',
    'href' => BASE_URL.'/auth/programas/save',
    'text' => 'Novo Programa'
);

$tableInformation = array(
    array(
        'index' => 'id',
        'format' => '',
        'descricao' => 'Id'
    ),
    array(
        'index' => 'desc_programa',
        'format' => 'nameFormatter',
        'descricao' => 'Programas'
    ),
    array(
        'index' => 'operate',
        'format' => 'operateFormatter',
        'descricao' => 'Operações',
        'events' => 'operateEvents'
    ),
);

$addIcon[] = array(
		'url' => BASE_URL.'/auth/programas/save',
		'title' => 'Editar',
		'classButton' => 'glyphicon glyphicon-pencil',
		'classHref' => 'edit',
);
$addIcon[] = array(
		'url' => BASE_URL.'/auth/programas/delete',
		'title' => 'Excluir',
		'classButton' => 'glyphicon glyphicon-trash',
		'classHref' => 'remove',
);

echo $this->partial('partials/datatable/template.phtml', array('breadcrumbs' => $breadcrumbs,
    'newButton' => $newButton,
    'addIcon' => $addIcon,
    'tableInformation' => $tableInformation,
));
?>


