<?php

$breadcrumbs[] = array(
    'url' => BASE_URL . '/auth/programas/index',
    'title' => 'Programas',
    'text' => 'Programas'
);
$breadcrumbs[] = array(
    'url' => BASE_URL . '/auth/programas/save',
    'title' => 'Novo Programa',
    'text' => 'Novo Programa'
);
$partialElements[] = array(
    'name' => 'id_filial',
    'label' => $this->formLabel($form->get('id_filial')->setLabelAttributes(array('for' => 'filial'))),
    'input' => $this->formSelect($form->get('id_filial')),
);
$partialElements[] = array(
    'name' => 'id_modulo',
    'label' => $this->formLabel($form->get('id_modulo')->setLabelAttributes(array('for' => 'modulo'))),
    'input' => $this->formSelect($form->get('id_modulo')),
);
$partialElements[] = array(
    'name' => 'desc_programa',
    'label' => $this->formLabel($form->get('desc_programa')->setLabelAttributes(array('for' => 'programa'))),
    'input' => $this->formInput($form->get('desc_programa'))
);

$partialElements[] = array(
    'name' => 'controller_programa',
    'label' => $this->formLabel($form->get('controller_programa')->setLabelAttributes(array('for' => 'Controlador do programa'))),
    'input' => $this->formInput($form->get('controller_programa')),
);

$partialElements[] = array(
    'name' => 'id',
    'input' => $this->formHidden($form->get('id'))
);
$checkbox = $form->checkbox;
$help = 'Nesta tela é feito o cadastro de Programas. Campos com * são obrigatórios! ';

echo $this->partial('/partials/form/template.phtml', array(
    'breadcrumbs' => $breadcrumbs,
    'titlePage' => 'Novo Programa',
    'partialElements' => $partialElements,
    'form' => $form,
    'help' => $help,
    'checkbox' => $checkbox
));
?>