<?php
if ($this->dados) {
    echo '<div>';
    foreach ($this->dados as $dado) {
        $checked = '';
        foreach ($this->dados_selecionadas as $dado_sel) {
            if ($dado_sel[$this->idColumnSelecionado] == $dado[$this->idColumn]) {
                $checked = 'active';
                break;
            }
        }
        echo "<label class='form-checkbox form-icon $checked'><input type='checkbox'  name='$this->name[]' value='" . $dado[$this->idColumn] . "' />" . $dado[$this->descColumn] . "</label>";
    }
    echo '</div>';
} else {
    ?>
    <div>
        <label for=""></label>
        <span class="info clearfix"><?php echo "<img src='/images/exclamacao_cyan.png' />" . $this->msg ?></span>

    </div>
<?php
}
exit;
?>