<?php

$breadcrumbs[] = array(
    'url' => BASE_URL . '/auth/usuario-perfil/index',
    'title' => 'Usuário Perfil',
    'text' => 'Usuário perfil'
);
$breadcrumbs[] = array(
    'url' => BASE_URL . '/auth/usuario-perfil/save',
    'title' => 'Vincular usuário a perfil',
    'text' => 'Vinculad usuário a perfil'
);
$partialElements[] = array(
    'name' => 'id_usuario',
    'label' => $this->formLabel($form->get('id_usuario')->setLabelAttributes(array('for' => 'id_usuario'))),
    'input' => $this->formSelect($form->get('id_usuario'))
);

$help = 'Nesta tela é atribuído um perfil ao usuário escolhido, podendo ser Administrador ou Admin de Testes. Os campos com * são obrigatórios';

$checkbox = $form->checkbox;

$partialElements[] = array(
    'name' => 'id',
    'input' => $this->formHidden($form->get('id'))
);

echo $this->partial('partials/form/template.phtml', array('breadcrumbs' => $breadcrumbs,
    'titlePage' => 'Vincular Usuário Perfil',
    'partialElements' => $partialElements,
    'form' => $form,
    'help' => $help,
    'checkbox' => $checkbox));
?>
<script type="text/javascript">
    function reload() {
        setTimeout(function () { // quando o timer for disparado...
            $("#id_usuario").trigger("chosen:updated");
        }, 400);

    }

    function checkbox() {
        $("label.form-checkbox").each(function() {
            $("label.form-checkbox").removeClass('active');
        });
        var user = $('#id_usuario').val();
        $.post('<?php echo BASE_URL; ?>/auth/usuarioperfil/set-ajax',
            {
                usuario: user
            }, function(d) {
                var aux = d.split(":");
                var inputs = document.getElementsByTagName('input');
                var x=0;
                for (var i = 1; i < aux.length; i++) {
                    var n = aux[i].replace(/[^\d]+/g, '');
                    for (x = 0; x < inputs.length; x++) {
                        if(inputs[x].name=='id_perfil[]')
                            if(inputs[x].value==n){
                                inputs[x].checked=true;
                                break;
                            }
                    }
                    document.getElementById(n).className = 'form-checkbox form-icon active';
                }
            });
    }

</script>

