<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else { ?>
                    <li class="active"><?php echo $breadcrumb['text']; ?></li>
                    <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<!-- ##### HEAD DA PAGINA #####-->
<?php if (isset($this->head)) { ?>
    <div id="page-title">
        <h1 class="page-header text-overflow"><?php echo $this->head; ?>
    </div>
<?php } ?>
<!-- ##### FIM DA HEAD #####-->

<div id="page-content">        
    <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
    <!--===================================================-->
    <input id="demo-sw-checkstate" type="hidden">
    <input id="demo-sw-checkstate-field"  type="hidden">

    <?php
    echo $this->form()->openTag($this->form);
    $messageError = $this->form->getMessages();
    ?>                                            
    <div class="row">
        <div class="eq-height">
            <div class="col-md-12 col-lg-12">
                <div class="tab-base">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#demo-lft-tab-1">Dados gerais</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-2">Emitente</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-3">Destinatário</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-4">Cálculo do imposto</a></li>
                        <li><a data-toggle="tab" href="#demo-lft-tab-5">Transportador</a></li>
                    </ul>
                    <div class="tab-content">
                        <?php
                        for ($i = 1; $i <= 5; $i++) {
                            switch ($i) {
                                case 1: $num = "demo-lft-tab-1";
                                    $grupo = "dados_nota";
                                    break;
                                case 2: $num = "demo-lft-tab-2";
                                    $grupo = "emitente";
                                    break;
                                case 3: $num = "demo-lft-tab-3";
                                    $grupo = "destinatario";
                                    break;
                                case 4: $num = "demo-lft-tab-4";
                                    $grupo = "calculo_imposto";
                                    break;
                                case 5: $num = "demo-lft-tab-5";
                                    $grupo = "dados_transportador";
                                    break;
                            }
                            $class = $i == 1 ? "tab-pane fade active in" : "tab-pane fade";
                            ?>
                            <div id="<?= $num ?>" class="<?= $class ?>">
                                <div class="panel-body">
                                    <table class="table table-striped">
                                        <tbody>
                                            <?php
                                            foreach ($this->partialElements as $chave => $element) {
                                                if ($element['grupo'] == $grupo) {
                                                    echo "<tr>";
                                                    if (isset($element['label'])) {
                                                        echo "<td>" . $element['label'] . "</td>";
                                                    }
                                                    if (isset($element['input'])) {
                                                        echo "<td>" . $element['input'] . "</td>";
                                                    }
                                                    echo "</tr>";
                                                }
                                            }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>                     
    <div class="panel">
        <div id="append" class="panel-body">        
            <div class="bootstrap-table">
<?php if (isset($this->newButton)) { ?>
                    <div class="panel-footer text-left">
                        <a class="btn btn-lg btn-primary" href='<?php echo $this->newButton['href'] ?>'><?php echo $this->newButton['text'] ?></a>
                    </div>
<?php } ?>
                <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-sort-name="id" data-sort-order="desc" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1">
                    <thead>
                        <tr>   
                            <?php foreach ($this->tableInformation as $th) { ?>    
                                <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php
                                if (isset($th['events'])) {
                                    echo $th['events'];
                                }
                                ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
                                    <?php
                                }
                                ?>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="panel-footer text-right">
                <?php
                echo $this->formButton($this->form->get('cancelar'));
                ?>
            </div>
<?php echo $this->form()->closeTag($this->form); ?>
        </div>
    </div>
</div>

<script>
    $JQuery(function() {
    $JQuery('[name="refresh"]').click(function() {
    var aux = '<?php echo $this->breadcrumbs[0]['url'] . '/ajax/1'; ?>';
            $('#demo-table').bootstrapTable('refresh', {url: aux});
    });
    });
            function nameFormatter(value, row) {
            if (value)
                    return '<a href="<?php echo $this->addIcon[0]['url']; ?>/id/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
                    return '-';
            }
    function nameFormatterTxt(value, row) {
    if (value)
            return '<a href="<?php echo $this->addIcon[0]['url']; ?>/txt/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
            return '-';
    }
    function operateFormatter(value, row, index) {
    return [
<?php foreach ($this->addIcon as $item) { ?>
        '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" title="<?php echo $item['title']; ?>">',
                '<i class="<?php echo $item['classButton']; ?>"></i>',
                '</a>&nbsp;&nbsp;&nbsp;',
<?php } ?>
    ].join('');
    }

    window.operateEvents = {
<?php
foreach ($this->addIcon as $item) {
    if ($item['classHref'] == 'remove') {
        ?>
            'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            if (confirm('Deseja deletar este registro?') == true){
            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                    console.log(value, row, index);
            }
            },
    <?php } else { ?>
            'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                    console.log(value, row, index);
            },
    <?php } ?>
<?php } ?>
    };
</script>
