<?php

/**
 * Controlador Pessoas
 * @data 17-04-2013
 * @category Application 
 * @package Controller 
 * @author  Willian Gustavo Mendo <willianmendo@unochapeco.edu.br>
 */
$breadcrumbs = array();
$breadcrumbs[0]['url'] = BASE_URL.'/auth/usuarios/index/page/1';
$breadcrumbs[0]['title'] = 'Usuários';
$breadcrumbs[0]['text'] = 'Usuários';

$head = 'Usuários';

$newButton = array();
$newButton['title'] = 'Novo Usuário';
$newButton['href'] = BASE_URL."/auth/usuarios/save";
$newButton['text'] = "Novo Usuário";
//Passar ação padrão primeiro.
$addIcon[] = array(
		'url' => BASE_URL.'/auth/usuarios/save',
		'title' => 'Editar',
		'classButton' => 'glyphicon glyphicon-pencil',
		'classHref' => 'edit',
);
$addIcon[] = array(
		'url' => BASE_URL.'/auth/usuarios/delete',
		'title' => 'Excluir',
		'classButton' => 'glyphicon glyphicon-trash',
		'classHref' => 'remove',
);

$tableIndex = array();
$i = 0;
foreach ($json[0] as $chave => $j) {
    $index[$i] = $chave;
    $i++;
}

$tableInformation = array(
    array('index' => $index[0],
        'format' => '',
        'descricao' => 'Id',
    ),
    array('index' => $index[1],
        'format' => 'nameFormatter',
        'descricao' => 'Nome',
    ),
    array('index' => $index[2],
        'format' => '',
        'descricao' => 'Login'
    ),
    array('index' => $index[3],
        'format' => '',
        'descricao' => 'Email',
    ),
    array('index' => $index[4],
        'format' => 'statusFormatter',
        'descricao' => 'Status',
    ),
    array('index' => $index[5],
        'format' => 'dateFormatter',
        'descricao' => 'Data de ativação',
    ),
    array('index' => $index[6],
        'format' => 'dateFormatter',
        'descricao' => 'Data de desativação',
    ),
    array('index' => 'operate',
        'format' => 'operateFormatter',
        'descricao' => 'Operações',
        'events' => 'operateEvents'
    ),
);
echo $this->partial('/partials/datatable/template.phtml', array(
	'breadcrumbs' => $breadcrumbs,
    'head' => $head,
    'newButton' => $newButton,
	'addIcon' => $addIcon,
    'tableInformation' => $tableInformation
));
?>