<div class="row">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5>Pessoas</h5>
            </div>
            <div class="panel-body">
                <a href="<?= BASE_URL ?>/auth/usuarios/save" class="btn btn-default">
                    Nova Pessoa
                </a>
                <a href="<?= BASE_URL ?>/auth/auth/logout" class="btn btn-default">
                    Logout
                </a>
                <table class="table table-hover table-bordered table-striped table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Data de Nascimento</th>
                            <th>Sexo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($pessoas as $pessoa) { ?>
                        <tr>
                            <td><?= $pessoa->getNome();?></td>
                            <td><?= $pessoa->getDataNascimento()->format('d/m/Y');?></td>
                            <td><?= $pessoa->getSexo();?></td>
                            <td>
                                <a href="<?= BASE_URL?>/auth/usuarios/save/id/<?= $pessoa->getId()?>">ED</a>
                                <a href="<?= BASE_URL?>/auth/usuarios/delete/id/<?= $pessoa->getId()?>">EX</a>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>

</div>