<?php
$breadcrumbs = array();
$breadcrumbs[] = array(
    'url' => BASE_URL . "/auth/usuarios/index",
    'title' => "Usuários",
    'text' => "Usuários",
);
$breadcrumbs[] = array(
    'url' => BASE_URL . "/auth/usuarios/save",
    'title' => "Save",
    'text' => "Novo Usuário",
);
$partialElements[] = array(
    'name' => 'nome',
    'label' => $this->formLabel($form->get('nome')->setLabelAttributes(array('for' => 'nome'))),
    'input' => $this->formInput($form->get('nome')),
);
$partialElements[] = array(
    'name' => 'login',
    'label' => $this->formLabel($form->get('login')->setLabelAttributes(array('for' => 'login'))),
    'input' => $this->formInput($form->get('login')),
);
$partialElements[] = array(
    'name' => 'email',
    'label' => $this->formLabel($form->get('email')->setLabelAttributes(array('for' => 'email'))),
    'input' => $this->formInput($form->get('email')),
);
$partialElements[] = array(
    'name' => 'senha',
    'label' => $this->formLabel($form->get('senha')->setLabelAttributes(array('for' => 'senha'))),
    'input' => $this->formInput($form->get('senha')),
);
$partialElements[] = array(
    'name' => 'ativo',
    'label' => $this->formLabel($form->get('ativo')->setLabelAttributes(array('for' => 'ativo'))),
    'input' => $this->formSelect($form->get('ativo')),
);
$partialElements[] = array(
    'name' => 'id',
    'input' => $this->formHidden($form->get('id')),
);
$checkbox = $form->checkbox;
$help = 'Cadastro ou alteração de usuários. Campos com * são obrigatórios!';
echo $this->partial('/partials/form/template.phtml', array(
    'breadcrumbs' => $breadcrumbs,
    'titlePage' => 'Novo Usuário',
    'partialElements' => $partialElements,
    'form' => $form,
    'help' => $help,
    'checkbox' => $checkbox,
));
?>
<script type="text/javascript">
    $JQuery(document).ready(function () {
        var inputs = document.getElementsByTagName('input');
        var x = 0;
        var valores = <?php echo json_encode($checked['perfis']); ?>;
        for (x = 0; x < inputs.length; x++) {
            if (inputs[x].name == 'perfis[]') {
                if (valores[inputs[x].value] == inputs[x].value)
                    inputs[x].checked = true;
            }
        }
        if ('<?= $role; ?>' === 'USUARIO') {
            $('div.checkbox').parent().hide();
        }
    });
</script>