
<?php

$breadcrumbs = array();
$breadcrumbs[0]['url'] = BASE_URL."/auth/auth";
$breadcrumbs[0]['title'] = "Login";
$breadcrumbs[0]['text'] = "Login";
$breadcrumbs[1]['url'] = BASE_URL."/auth/padrao/save";
$breadcrumbs[1]['title'] = "Programa Padrão";
$breadcrumbs[1]['text'] = "Programa Padrão";

$partialElements = array();

$partialElements[1]['name'] = 'programa'; 
$partialElements[1]['label'] = $this->formLabel($form->get('programa')->setLabelAttributes(array('for' => 'Programa ')));
$partialElements[1]['input'] = $this->formSelect($form->get('programa'));

$help = 'Aqui é possível selecionar um programa para ser seu padrão!';

echo $this->partial('partials/form/template.phtml', array(
    'breadcrumbs' => $breadcrumbs,
    'partialElements' => $partialElements,
    'form' => $form,
    'help' => $help,
    ));
?>
