<style> #box {width:80em; border: solid 1px; border-color: #c9c9c9; border-radius: 4px; margin-left: 15px;}</style>
<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                    <?php
                } else {
                    if (isset($modal)) {
                        ?>
                        <li><a href="#" title="Opções" onclick="mostrarModals();"><?php echo $modal; ?></a></li>
                    <?php } ?>
                    <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
                    <?php
                }
            }
            ?>
        </ol>
    <?php } ?>

<!--<div id="content-container" style='margin-left: -46%; margin-top:-4%;'>-->
    <div id="page-title">
        <h1 class="page-header text-overflow">

            <?php
            if ($mensagem->tipo_mensagem == 'Notificação') {
                $label = 'success';
            } else if ($mensagem->tipo_mensagem == 'Alerta') {
                $label = 'danger';
            } else if ($mensagem->tipo_mensagem == 'Mensagem') {
                $label = 'info';
            } else if ($mensagem->tipo_mensagem == 'Solicitação') {
                $label = 'warning';
            }
            ?>

            <span class="label label-normal label-<?= $label ?>"><?= $mensagem->tipo_mensagem ?></span>
<?= $mensagem->assunto ?>
        </h1>

        <!--Searchbox-->
    </div>
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <!--End page title-->

    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">

        <!-- VIEW MESSAGE -->
        <!--===================================================-->
        <div class="panel panel-default panel-left">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-7">

                        <!--Sender Information-->
                        <div class="media">
                            <span class="media-left">
                                <img src="/images/logo_favero.png" class="img-circle img-sm" alt="<?= $mensagem->autor ?>">
                            </span>
                            <div class="media-body">
                                <div class="text-bold"><?= $mensagem->autor ?></div>
                                <small class="text-muted">Fávero & Associados</small>
                            </div>
                        </div>
                    </div>
                    <hr class="hr-sm visible-xs">
                    <div class="col-sm-5 clearfix">

                        <!--Details Information-->
                        <div class="pull-right text-right">
                            <p class="mar-no"><small class="text-muted"><?= $mensagem->data_criacao->format('d-m-Y H:i:s') ?></small></p>
<?php if (isset($mensagem->anexo) && $mensagem->anexo != null && isset($retirar)) { ?>
                                <a onclick="downloadAnexo();" href="#">
                                    <strong><?= $mensagem->anexo->nome_arquivo ?></strong>
                                    <i class="fa fa-paperclip fa-lg fa-fw"></i>
                                </a>
<?php } ?>
                        </div>
                    </div>
                </div>
                <div class="row pad-ver">
                    <div class="col-xs-7">

                        <!--Mail toolbar-->
                        <button class="btn btn-default" onclick="imprimir();"><i class="fa fa-print"></i></button>
                        <button class="btn btn-default" onclick="excluir();"><i class="fa fa-trash"></i></button>
<?php if ($mensagem->tipo_mensagem == 'Solicitação') { ?>
                            <div class="btn-group btn-group">
                                <button class="btn btn-success" title="Autorizar solicitação" onclick="permissao(1);"><i class="fa fa-check"></i></button>
                                <button class="btn btn-danger" title="Negar solicitação" onclick="permissao(2);"><i class="fa fa-exclamation-circle"></i></button>
                            </div>
<?php } ?>
                    </div>
                    <div class="col-xs-5 clearfix">
                        <div class="pull-right">

                            <!--Reply & forward buttons-->
<!--                            <div class="btn-group btn-group">
                                <a class="btn btn-default" href="#" onclick="nextMessage()">
                                    <i class="fa fa-reply"></i>
                                </a>
                                <a class="btn btn-default" href="#" onclick="previousMessage()">
                                    <i class="fa fa-share"></i>
                                </a>
                            </div>-->
                        </div>
                    </div>
                </div>

                <!--Message-->
                <!--===================================================-->
                <div class="pad-all bord-all bg-gray-light">

                    <blockquote class="text-muted">
<?= $mensagem->mensagem; ?>
                    </blockquote>
                    <br><br>
                    Atenciosamente,
                    <br>
                    <strong><?= $mensagem->autor ?></strong><br>
                    Fávero & Associados<br>
                </div>
                <!--===================================================-->
                <!--End Message-->

                <!-- Attach Files-->
                <!--===================================================-->


                <div class="pad-ver">
<?php if (isset($anexos) && $anexos != null) { ?>
                        <h4><i class="fa fa-paperclip fa-fw"></i> Anexos <span></span></h4>
                        <ul class="mail-attach-list list-ov">
                            <?php $total = count($anexos);
                            $i = 1;
                            foreach($anexos as $key => $anexo){ ?>
                            <li class="clearfix">
                                <?php if($total == $i){?>
                                    <div class="mail-attach-btn"><a onclick="downloadAnexo(null);" href="#" class="btn btn-purple btn-sm">Baixar zip com tudo</a></div>
                                <?php } $i++; ?>
                                <!--File information-->
                                <div class="mail-attach-file">
                                    <span class="mail-attach-label">
                                        <span class="label label-info text-uppercase"><?= strstr($anexo->tipo, '/', true) ?></span>
                                    </span>
                                    <div class="media-body">
                                        <div class="text-bold"><a onclick="downloadAnexo(<?= $anexo->id ?>);" href="#"> <?= $anexo->nome_arquivo ?></a></div>
                                        <small class="text-muted"><?= number_format($anexo->tamanho/1024,2) ?> kB</small>
                                    </div>
                                </div>
                            </li>     
                            <?php } ?>
                        </ul>
<?php } ?>
                </div>

                <!--===================================================-->
                <!-- End Attach Files-->


                <!--Quick reply : Summernote Placeholder -->
                <div id="demo-mail-textarea" class="mail-message-reply bg-gray-light">
                    <h4><i class="fa fa-reply fa-fw"></i> Responder <span></span></h4>
                    <textarea id='resposta' style="width: 100%; height: 80px;" placeholder="Escreva aqui uma resposta para essa mensagem"></textarea>
                </div>

                <!--Send button-->
                <div class="pad-ver">
                    <button id="demo-mail-send-btn" onclick="voltar();" type="button" class="btn btn-danger">
                        <span class="fa fa-chevron-left"></span>
                        Voltar
                    </button>
                    <button id="demo-mail-send-btn" onclick="responder($JQuery('#resposta').val());" type="button" class="btn btn-primary">
                        <span class="fa fa-paper-plane"></span>
                        Enviar
                    </button>
                </div>
            </div>
        </div>
        <!--===================================================-->
        <!-- END VIEW MESSAGE -->


    </div>

    <aside id="aside-container">
        <div id="aside">
            <div class="nano">
                <div class="nano-content" id='menu_email'>

                    <div class="pad-hor">
                        <h4 class="text-thin">Mensagens</h4>
                        <a href="<?php echo BASE_URL . "/auth/mensagens/save" ?>" class="btn btn-block btn-info">
                            Nova mensagem
                        </a>
                    </div>
                    <hr>
                    <div class="list-group bg-trans bord-no">
                        <a href="<?php echo BASE_URL . "/auth/mensagens/index" ?>" class="list-group-item">
                            <span class="badge badge-primary pull-right"><?php if ($totais['todas'] != 0) echo $totais['todas'] ?></span><i class="fa fa-inbox fa-fw"></i> Caixa de entrada
                        </a>
                        <a href="<?php echo BASE_URL . "/auth/mensagens/index/unread/1" ?>" class="list-group-item">
                            <span class="badge badge-success pull-right"><?php if ($totais['nao_lidas'] != 0) echo $totais['nao_lidas'] ?></span><i class="fa fa-envelope-o fa-fw"></i> Não lidas
                        </a>
                        <a href="<?php echo BASE_URL . "/auth/mensagens/index/read/1" ?>" class="list-group-item">
                            <span class="badge badge-info pull-right"><?php if ($totais['lidas'] != 0) echo $totais['lidas'] ?></span><i class="fa fa-envelope fa-fw"></i> Lidas
                        </a>
                        <a href="<?php echo BASE_URL . "/auth/mensagens/index/starred/1" ?>" class="list-group-item">
                            <span class="badge badge-warning pull-right"><?php if ($totais['estrelas'] != 0) echo $totais['estrelas'] ?></span><i class="fa fa-star fa-fw"></i> Com estrela
                        </a>                   
                        <a href="<?php echo BASE_URL . "/auth/mensagens/index/sent/1" ?>" class="list-group-item"><span class="badge badge-danger pull-right"><?php if ($totais['enviadas'] != 0) echo $totais['enviadas'] ?></span><i class="fa fa-send fa-fw"></i> Enviados</a>
                    </div>
                    <hr>                                                  
                </div>
            </div>
        </div>
    </aside>


    <!-- ##### FIM DOS BREADCRUMBS #####-->
    <!--
    <div id="page-content">
        <div class="panel">
<?php // if (isset($this->help)) {  ?>
                <div class="panel-heading">
                    <h3 class="panel-title" style='font-size:2em;'><spam><i class='fa fa-icon fa-envelope' style='margin-right:10px;'></i></spam><strong>Assunto: </strong><?php // echo $this->help   ?></h3>
                </div>
    <?php // } ?>
<?php // if (isset($this->mensagem)) {  ?>
                <div class="panel-body">
                    <div id="box">
                        <h3 style='font-size:2em; margin-left:15px; color: #2e2e2e'><?php // echo $this->mensagem   ?></h3>
                    </div>
                </div>
<?php // }  ?>
            <div class="panel-footer">
                <div class="panel-title">
                    <input type="button" class="btn btn-danger" style="float: left; margin-top: 0.5%;" value="Voltar" id="ignorar" onclick="voltar();"/>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function voltar() {
            window.history.go(-1);
        }
    </script>-->

