<style>
    .panel-body{
        margin-top: 5px;
    }
    .cls-content-sm {
        color : #ffffff !important;
    }
</style>
		<!-- LOGIN FORM -->
	<!--===================================================-->
	<div class="cls-content">
		<div class="cls-content-sm">
			<div class="panel-body">
				<p class="pad-btm" style="font-size: 1.4em; font-weight: bold">Efetue Login</p>
				<?php echo $this->form()->openTag($form); ?>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-user"></i></div>
							<?php echo $this->formRow($form->get('login')); ?>
						</div>
					</div>


					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
							<?php echo $this->formRow($form->get('senha')); ?>
						</div>
					</div>


					<div class="row">
						<div class="col-xs-8 text-left checkbox">
							<label class="form-checkbox form-icon">
							<?php echo $this->formRow($form->get('checkbox')); ?>
							</label>
						</div>

						<div class="col-xs-4">
							<div class="form-group text-right">
							<?php echo $this->formRow($form->get('Submit')); ?>
							</div>
						</div>
					</div>
			   <?php echo $this->form()->closeTag($form); ?>
			</div>
		</div>

		<div class="pad-ver">
			<a href="<?php echo BASE_URL; ?>/auth/auth/recupera-senha" class="btn-link mar-rgt">Esqueceu sua senha?</a>
			<!-- <a href="pages-password-reminder.html" class="btn-link mar-rgt">Forgot password ?</a>
			<a href="pages-register.html" class="btn-link mar-lft">Create a new account</a> -->
		</div>
	</div>

	<!--===================================================-->
	<!-- END OF LOGIN FORM -->

        <label class="msg">
            <?php
            if ($this->session()->offsetGet('error')) {
                echo $this->session()->offsetGet('error');
                $this->session()->offsetUnset('error');
            }
            ?>
        </label>