<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Login</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formRow($form->get('login')); ?>
                <?php echo $this->formRow($form->get('senha')); ?>
                <?php echo $this->formRow($form->get('checkbox')); ?>
                <?php echo $this->formRow($form->get('Submit')); ?>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>

</div>
