<div class="create-account">
    <div class="panel-heading">
        <h2 class="section-title">Login</h2>
    </div>
    <div class="panel-body">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formRow($form->get('email')); ?>
        <?php echo $this->formRow($form->get('senha')); ?>
        <?php echo $this->formRow($form->get('checkbox')); ?>
        <?php echo $this->formRow($form->get('Submit')); ?>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>
