		<!-- LOGIN FORM -->
	<!--===================================================-->
	<div class="cls-content">
		<div class="cls-content-sm panel">
			<div class="panel-body">
				<p class="pad-btm">Altere Sua Senha</p>
				<?php echo $this->form()->openTag($form); ?>
					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-user"></i></div>
							<?php echo $this->formRow($form->get('login')); ?>
						</div>
					</div>


					<div class="form-group">
						<div class="input-group">
							<div class="input-group-addon"><i class="fa fa-asterisk"></i></div>
							<?php echo $this->formRow($form->get('senha')); ?>
						</div>
					</div>


					<div class="form-group text-right">
					    <?php echo $this->formRow($form->get('Submit')); ?>
            			<?php echo $this->formRow($form->get('cancelar')); ?>
					</div>
				<?php echo $this->form()->closeTag($form); ?>
			</div>
		</div>
	</div>

	<!--===================================================-->
	<!-- END OF LOGIN FORM -->
