<style>
    .active-floatlabel{
        padding-top: 13px !important;
    }
</style>
<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php
                } else {
                    if (isset($modal)) {
                        ?>
                        <li><a href="#" title="Opções" onclick="mostrarModals();"><?php echo $modal; ?></a></li>
                    <?php } ?>
                    <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
                <?php
                }
            }
            ?>
        </ol>
    <?php }
if (isset($this->smartbar))
    if ($this->smartbar) {
        $keys = array_keys($this->smartbar);
        $endKey = end($keys);
        ?>
        <ul class="wz-nav-on wz-steps" style="margin-left:-2%;margin-top: -15px; margin-bottom: -25px;">
            <?php
            foreach ($this->smartbar as $chave => $smartbar) {
                if ($smartbar['url'] == '#')
                    $urlSmartbar = '#';
                else
                    $urlSmartbar = BASE_URL . $smartbar['url'];
                ?>
                <?php if (!isset($smartbar['active'])) { ?>
                    <li class="col-xs-1" style='margin-left:25px;'><a href="<?php echo $urlSmartbar; ?>" title="<?php echo $smartbar['title']; ?>">
                        <span class="icon-wrap icon-wrap-xs bg-<?php echo $smartbar['bgIcon']?>">
                            <i class="fa <?php echo $smartbar['icon']?> fa-2x"></i>
                        </span>
                            <p style="font-size: 12px;"><?php echo $smartbar['title']?></p>
                        </a>
                    </li>
                <?php
                } else { ?>
                    <li class="col-sm-1" style='margin-left:25px;'><a href="<?php echo $urlSmartbar; ?>" title="<?php echo $smartbar['title']; ?>"><span class="icon-wrap icon-wrap-xs bg-success"><i class="fa <?php echo $smartbar['icon']?> fa-2x"></i>
                        </span><p style="font-size: 12px;"><?php echo $smartbar['title']?></p>
                        </a></li>
                <?php
                }
            }
            ?>
        </ul>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->
<!---->


<div id="page-content">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->help; ?></h3>
        </div>
        <div class="panel-body">
            <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
            <!--===================================================-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">
            <!--===================================================-->
            <!-- END OF PAGE CONTENT -->
            <!-- BLOCK STYLED FORM FORM  -->
            <!--===================================================-->
            <?php
            echo $this->form()->openTag($this->form);
            $messageError = $this->form->getMessages();
            ?>
            <div id="append" class="panel-body">
                <?php if(isset($this->primeiraLinha)){ ?>
                <div class="row">
                    <div class="col-md-12 col-lg-12 eq-box-lg" style="background-color: white; margin-top:-15px; padding-bottom: 30px;">
                        <div class="row">
                            <?php
                            $classError = 'has-error has-feedback';
                            $errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
                            $cont = 0;
                            foreach ($this->primeiraLinha as $chave => $element) {
                                if (isset($element['id_div'])) {
                                    $idDiv = 'id="' . $element['id_div'] . '"';
                                } else {
                                    $idDiv = '';
                                }
                                if (isset($element['htmlElement'])) {
                                    $html = '<div>' . $element['htmlElement'] . '</div>';
                                } else {
                                    $html = '';
                                }
                                if (!isset($element['grupo'])) {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                                    ?>
                                    <?php if ($cont == 0) { ?>
                                        <div class="col-sm-<?php echo $this->pLinhaColunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                            <div <?php echo $idDiv ?> class="input-group mar-btm<?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                <?php
                                                if (!isset($element['none'])) {
                                                    if (isset($element['label']) && !isset($element['icon'])) {
                                                        echo $element['label'];
                                                    } else {
                                                        if (isset($element['icon']) && isset($element['nome'])) {
                                                            ?>
                                                            <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                    <i class="<?php echo $element['icon']; ?>" ></i>
                                                                </span>
                                                        <?php
                                                        }
                                                    }
                                                }
                                                ?>
                                                <?php
                                                if (isset($element['calendario'])) {
                                                    ?>
                                                    <div id="demo-dp-txtinput">
                                                        <?php echo $element['input'] ?>
                                                    </div>
                                                <?php
                                                } else if (!isset($element['type'])) {
                                                    echo $element['input'];
                                                    if (isset($messageError[$element['name']])) {
                                                        $messageErrorExib = array_pop($messageError[$element['name']]);
                                                        echo $errorIcon;
                                                        echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                    }
                                                } else {
                                                    ?>
                                                    <br>
                                                    <span class="btn btn-default btn-file">
                                        <?php
                                        echo $element['label'];
                                        echo $element['input'];
                                        ?>
                                    </span>
                                                <?php } ?>
                                                <span class="info clearfix">
                                    <?php
                                    if (isset($element['information']))
                                        echo $element['information'];
                                    else if (isset($element['information2']))
                                        echo $element['information'];
                                    ?>
                                </span>
                                            </div>
                                        </div>
                                        <?php
                                        $cont = 1;
                                    } else {
                                        ?>
                                        <div class="col-sm-<?php echo $this->pLinhaColunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                            <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                <?php
                                                if (!isset($element['none'])) {
                                                    if (isset($element['label']) && !isset($element['icon'])) {
                                                        echo $element['label'];
                                                    } else {
                                                        if (isset($element['icon']) && isset($element['nome'])) {
                                                            ?>
                                                            <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                <i class="<?php echo $element['icon']; ?>" ></i>
                                            </span>
                                                        <?php
                                                        }
                                                    }
                                                }
                                                ?>
                                                <?php
                                                if (isset($element['calendario'])) {
                                                    ?>
                                                    <div id="demo-dp-txtinput">
                                                        <?php echo $element['input'] ?>
                                                    </div>
                                                <?php
                                                } else if (!isset($element['type'])) {
                                                    echo $element['input'];
                                                    if (isset($messageError[$element['name']])) {
                                                        $messageErrorExib = array_pop($messageError[$element['name']]);
                                                        echo $errorIcon;
                                                        echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                    }
                                                } else {
                                                    ?>
                                                    <br>
                                                    <span class="btn btn-default btn-file">
                                        <?php
                                        echo $element['label'];
                                        echo $element['input'];
                                        ?>
                                    </span>
                                                <?php } ?>
                                                <span class="info clearfix">
                                    <?php
                                    if (isset($element['information']))
                                        echo $element['information'];
                                    else if (isset($element['information2']))
                                        echo $element['information'];
                                    ?>
                                </span>
                                            </div>
                                        </div>
                                        <?php
                                        $cont = 0;
                                    }
                                }
                            }
                            if (isset($radio)) {
                            foreach ($radio as $chave => $element) {
                                if (isset($element['id_div'])) {
                                    $idDiv = 'id="' . $element['id_div'] . '"';
                                } else {
                                    $idDiv = '';
                                }
                            }
                            if(!isset($element['colunas'])){ ?>
                                <div class="col-sm-<?= $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                            <?php } else { ?>
                                <div class="col-sm-6" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                            <?php } ?>
                                    <div <?php echo $idDiv ?> class="form-group">
                                        <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                                        <div class="radio">
                                            <!-- INLINE CHECKBOXES -->
                                            <!--===================================================-->
                                            <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                                <label class="form-radio form-icon active">
                                                    <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id'] . '-' . $chaves; ?>" value="<?php echo $chaves; ?>" type="radio"><?php echo $elements; ?>
                                                </label>
                                                <!--===================================================-->
                                            <?php } ?>
                                            <?php
                                            if (isset($messageError[$element['name']])) {
                                                $messageErrorExib = array_pop($messageError[$element['name']]);
                                                echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                            }
                                            ?>
                                        </div>
                                    </div>
                                </div>
                                <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <?php }
                    $cont = 0;
                    foreach ($this->partialElements as $chave => $element) {
                    if (isset($element['id_div'])) {
                        $idDiv = 'id="' . $element['id_div'] . '"';
                    } else {
                        $idDiv = '';
                    }
                    if (isset($element['htmlElement'])) {
                        $html = '<div>' . $element['htmlElement'] . '</div>';
                    } else {
                        $html = '';
                    }
                    ?>
                    <?php if ($cont == 0) {
                    if(!isset($element['colunas'])){
                    ?>
                    <div class="col-sm-<?= $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                        <?php } else { ?>
                        <div class="col-sm-6" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                            <?php } ?>
                            <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                <?php
                                if (!isset($element['none'])) {
                                    if (isset($element['label']) && !isset($element['icon'])) {
                                        echo $element['label'];
                                    } else {
                                        if (isset($element['icon']) && isset($element['nome'])) {
                                            ?>
                                            <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                        <i class="<?php echo $element['icon']; ?>" ></i>
                                                                    </span>
                                        <?php
                                        }
                                    }
                                }
                                ?>
                                <?php
                                if (isset($element['calendario'])) {
                                    ?>
                                    <div id="demo-dp-txtinput">
                                        <?php echo $element['input'] ?>
                                    </div>
                                <?php
                                } else if (!isset($element['type'])) {
                                    echo $element['input'];
                                    if (isset($messageError[$element['name']])) {
                                        $messageErrorExib = array_pop($messageError[$element['name']]);
                                        echo $errorIcon;
                                        echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                    }
                                } else {
                                    ?>
                                    <br>
                                    <span class="btn btn-default btn-file">
                                                                <?php
                                                                echo $element['label'];
                                                                echo $element['input'];
                                                                ?>
                                                            </span>
                                <?php } ?>
                                <span class="info clearfix">
                                                            <?php
                                                            if (isset($element['information']))
                                                                echo $element['information'];
                                                            else if (isset($element['information2']))
                                                                echo $element['information'];
                                                            ?>
                                                        </span>
                            </div>
                        </div>
                        <?php
                        $cont = 1;
                        } else {
                        if(!isset($element['colunas'])){
                        ?>
                        <div class="col-sm-<?= $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                            <?php } else { ?>
                            <div class="col-sm-6" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                <?php } ?>
                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (!isset($element['none'])) {
                                        if (isset($element['label']) && !isset($element['icon'])) {
                                            echo $element['label'];
                                        } else {
                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                ?>
                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                        <i class="<?php echo $element['icon']; ?>" ></i>
                                                                    </span>
                                            <?php
                                            }
                                        }
                                    }
                                    ?>
                                    <?php
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];

                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>

                                        <span class="btn btn-default btn-file">
                                        <?php
                                        echo $element['label'];
                                        echo $element['input'];
                                        ?>
                                    </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                    <?php
                                    if (isset($element['information']))
                                        echo $element['information'];
                                    else if (isset($element['information2']))
                                        echo $element['information'];
                                    ?>
                                </span>

                                </div>
                                <?php echo $html; ?>
                            </div>
                            <?php
                            $cont = 0;
                            }
                            }
                            if ($cont == 1)
                                echo '</div>';
                            echo '</div>';
                            if (isset($checkbox)) {
                                foreach ($checkbox as $chave => $element) {
                                    ?>
                                    <div id="switch" class="form-group">
                                        <?php if (!isset($element['class'])) { ?>
                                            <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                                            <div class="checkbox">
                                                <!-- INLINE CHECKBOXES -->
                                                <!--===================================================-->
                                                <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                                    <label class="form-checkbox form-icon active">
                                                        <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id']; ?>" value="<?php echo $chaves; ?>" type="checkbox"><?php echo $elements; ?>
                                                    </label>
                                                    <!--===================================================-->
                                                <?php } ?>
                                                <?php
                                                if (isset($messageError[$element['name']])) {
                                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                }
                                                ?>
                                            </div>
                                        <?php } else { ?>
                                            <input id="demo-sw-sz-lg" type="checkbox" checked>
                                            <span id="demo-sw-checkstate-field" class="label label-info">Servidor</span>
                                        <?php } ?>
                                    </div>
                                <?php
                                }
                            }
                            ?>
                            <div class="panel-footer text-right">
                                <?php $submitbutton = isset($this->btnSubmit) ? "$this->btnSubmit" : "Salvar" ?>
                                <button id="submitbutton" type="submit" class="btn btn-primary"><?= $submitbutton ?></button>
                                <?php
                                if (array_key_exists('cancelar', $this->form->getElements()))
                                    echo $this->formButton($this->form->get('cancelar'));
                                ?>
                            </div>
                            <?php echo $this->form()->closeTag($this->form); ?>
                            <!--===================================================-->
                            <!-- END OF BLOCK STYLED FORM FORM  -->

                            <!--====================================================-->
                            <!-- FILTERS -->

                            <div id="overlay">
                                <?php
                                if(isset($this->filter)){?>
                                    <div id="filter">
                                        <?php foreach($this->filter as $f) { ?>
                                            <label class="form-checkbox form-icon active form-text">
                                                <input name="<?php echo $f['name']; ?>[]" value="<?php echo $f['value']; ?>"
                                                       type="checkbox" onchange="<?php echo $f['funcao']; ?>"<?php if($f['check']) echo "checked"; ?>><?php echo $f['desc']; ?>
                                            </label>

                                        <?php } ?>
                                    </div>
                                <?php } ?>




                                <!--====================================================-->
                                <!-- END OF FILTERS -->

                                <div class="bootstrap-table">
                                    <?php if (isset($this->newButton)) { ?>
                                        <div class="panel-footer text-left">
                                            <a class="btn btn-lg btn-primary" href='<?php echo $this->newButton['href'] ?>'><?php echo $this->newButton['text'] ?></a>
                                        </div>
                                    <?php } ?>
                                    <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-sort-name="id" data-sort-order="desc" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1">
                                        <thead>
                                        <tr>
                                            <?php
                                            foreach ($this->tableInformation as $th) {
                                                if ($th['index'] == 'checkbox') {
                                                    ?>
                                                    <th data-align="center" data-sortable="false" data-checkbox="true"></th><?php } else { ?>
                                                    <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php
                                                    if (isset($th['events'])) {
                                                        echo $th['events'];
                                                    }
                                                    ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
                                                <?php
                                                }
                                            }
                                            ?>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <script src="<?php echo BASE_URL ?>/js/floatlabels.js" type="text/javascript"></script>
                <script>
                    $JQuery('input.floatlabel').floatlabel();
                    $JQuery(function() {
                        $JQuery('[name="refresh"]').click(function() {
                            var aux = '<?php echo $this->breadcrumbs[0]['url'] . '/ajax/1'; ?>';
                            $('#demo-table').bootstrapTable('refresh', {url: aux});
                        });
                    });
                    function nameFormatter(value, row) {
                        if (value)
                            return '<a href="<?php echo $this->addIcon[0]['url']; ?>/id/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
                        return '-';
                    }
                    function nameFormatterTxt(value, row) {
                        if (value)
                            return '<a href="<?php echo $this->addIcon[0]['url']; ?>/txt/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
                        return '-';
                    }
                    function operateFormatter(value, row, index) {
                        return [
                            <?php foreach ($this->addIcon as $item) {
                            if(isset($item['onClick'])){ ?>
                            '<a class="<?php echo $item['classHref']; ?>" href="#" onclick="<?php echo $item['onClick'] ?>" title="<?php echo $item['title']; ?>">',
                            <?php } else { ?>
                            '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" title="<?php echo $item['title']; ?>">',
                            <?php }?>
                            '<i class="<?php echo $item['classButton']; ?>"></i>',
                            '</a>&nbsp;&nbsp;&nbsp;',
                            <?php } ?>
                        ].join('');
                    }
                    function dateHourFormatter(value, row) {
                        var aux = value;
                        if (aux !== null){
                            var auxData = aux['date'].split(" ");
                            var a = auxData[0].split("-");
                            var b = auxData[1].split(":");
                            var data = a[2] + '-' + a[1] + '-' + a[0] + ' ' + b[0] + ':' + b[1];
                            console.log(data);
                            return '<span><i class="fa fa-clock-o"></i> ' + data + '</span>';
                        } else {
                            return '<span><i></i> </span>';
                        }
                    }

                    window.operateEvents = {
                        <?php
                        foreach ($this->addIcon as $item) {
                            if ($item['classHref'] == 'remove') {
                                ?>
                        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
                            if (confirm('Deseja deletar este registro?') == true){
                                window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                                console.log(value, row, index);
                            }
                        },
                        <?php } else { ?>
                        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
                            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                            console.log(value, row, index);
                        },
                        <?php } ?>
                        <?php } ?>
                    };
                </script>