<style>
    .active-floatlabel{
        padding-top: 13px !important;
    }
</style>
<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else { ?>
                    <li class="active"><?php echo $breadcrumb['text']; ?></li>
                <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<!-- ##### HEAD DA PAGINA #####-->
<?php if (isset($this->head)) { ?>
    <div id="page-title">
        <h1 class="page-header text-overflow"><?php echo $this->head; ?>
    </div>
<?php } ?>
<!-- ##### FIM DA HEAD #####-->

<div id="page-content">
    <div class="panel">
        <div id="page-content">
            <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
            <!--===================================================-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">

            <?php
            echo $this->form()->openTag($this->form);
            $messageError = $this->form->getMessages();
            ?>
            <div class="row">
                <?php
                $cont = 0;
                foreach ($this->partialElements as $chave => $element) {
                    if (isset($element['id_div'])) {
                        $idDiv = 'id="' . $element['id_div'] . '"';
                    } else {
                        $idDiv = '';
                    }
                    if (isset($element['htmlElement'])) {
                        $html = '<div>' . $element['htmlElement'] . '</div>';
                    } else {
                        $html = '';
                    }
                    if (!isset($element['grupo'])) {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                        ?>
                        <?php if ($cont == 0) { ?>
                            <div class="col-sm-<?php echo $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                <div <?php echo $idDiv ?> class="input-group mar-btm<?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (!isset($element['none'])) {
                                        if (isset($element['label']) && !isset($element['icon'])) {
                                            echo $element['label'];
                                        } else {
                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                ?>
                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                    <i class="<?php echo $element['icon']; ?>" ></i>
                                                </span>
                                            <?php
                                            }
                                        }
                                    }
                                    ?>
                                    <?php
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>
                                        <span class="btn btn-default btn-file">
                                            <?php
                                            echo $element['label'];
                                            echo $element['input'];
                                            ?>
                                        </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                        <?php
                                        if (isset($element['information']))
                                            echo $element['information'];
                                        else if (isset($element['information2']))
                                            echo $element['information'];
                                        ?>
                                    </span>
                                </div>
                            </div>
                            <?php
                            $cont = 1;
                        } else {
                            ?>
                            <div class="col-sm-<?php echo $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (!isset($element['none'])) {
                                        if (isset($element['label']) && !isset($element['icon'])) {
                                            echo $element['label'];
                                        } else {
                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                ?>
                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                    <i class="<?php echo $element['icon']; ?>" ></i>
                                                </span>
                                            <?php
                                            }
                                        }
                                    }
                                    ?>
                                    <?php
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>
                                        <span class="btn btn-default btn-file">
                                            <?php
                                            echo $element['label'];
                                            echo $element['input'];
                                            ?>
                                        </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                        <?php
                                        if (isset($element['information']))
                                            echo $element['information'];
                                        else if (isset($element['information2']))
                                            echo $element['information'];
                                        ?>
                                    </span>
                                </div>
                            </div>
                            <?php
                            $cont = 0;
                        }
                    }
                }
                if (isset($checkbox)) {
                    foreach ($checkbox as $chave => $element) {
                        if (isset($element['id_div'])) {
                            $idDiv = 'id="' . $element['id_div'] . '"';
                        } else {
                            $idDiv = '';
                        }
                    }
                    ?>
                    <div class="col-sm-6">
                        <div <?php echo $idDiv ?> class="form-group">
                            <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                            <div class="checkbox">
                                <!-- INLINE CHECKBOXES -->
                                <!--===================================================-->
                                <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                    <label class="form-checkbox form-icon active">
                                        <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id'] . '-' . $chaves; ?>" value="<?php echo $chaves; ?>" type="checkbox"><?php echo $elements; ?>
                                    </label>
                                    <!--===================================================-->
                                <?php } ?>
                                <?php
                                if (isset($messageError[$element['name']])) {
                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                <?php
                }
                ?>
                <fieldset id="itens-nota" style="margin-top: 23%; width: 98%;">
                    <legend>Itens da Nota Fiscal:</legend>
                    <div class="row">
                        <div class="col-sm-1" style="width: 14%; margin-top: 15px; max-height: 45px; margin-bottom: -15px; margin-left: -16px;">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Produto/Serviço">
                                        <i class="fa fa-tag fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="produto_servico" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="produto_servico-0" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Prod./Serv." data-class="red-label" placeholder="Prod./Serv." name="itens[0][produto_servico]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                        <div class="col-sm-3" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px; margin-left: -25px">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Detalhes do Item">
                                        <i class="fa fa-list fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="detalhe_item" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="detalhe_item-0" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Detalhes do Item" data-class="red-label" placeholder="Detalhes do Item" name="itens[0][detalhe_item]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                        <div class="col-sm-1" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px; width: 123px; margin-left: -25px">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Qtd">
                                        <i class="fa fa-tags fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="quantidade" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="quantidade-0" onblur="calcular(0);" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Qtd" data-class="red-label" placeholder="Qtd" name="itens[0][quantidade]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                        <div class="col-sm-1" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px; margin-left: -25px; width: 16%">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Custo">
                                        <i class="fa fa-usd fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="custo" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="custo-0" onblur="calcular(0);" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Custo" data-class="red-label" placeholder="Custo" name="itens[0][custo]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                        <div class="col-sm-1" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px; margin-left: -25px; width: 16%">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Sub Total">
                                        <i class="fa fa-usd fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="subtotal" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="subtotal-0" readonly="readonly" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Sub Total" data-class="red-label" placeholder="Sub Total" name="itens[0][subtotal]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                        <div class="col-sm-1" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px; margin-left: -25px; width: 15%">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Valor ICMS">
                                        <i class="fa fa-usd fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="valor_icms" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="valor_icms-0" onblur="calcularValorTotalIcms(0);" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor ICMS" data-class="red-label" placeholder="ICMS" name="itens[0][valor_icms]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                        <div class="col-sm-1" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px; margin-left: -25px; margin-right: -25px; width: 15%">
                            <div class="input-group mar-btm ">
                                    <span class="input-group-addon" title="Valor IPI">
                                        <i class="fa fa-usd fa-lg"></i>
                                    </span>
                                <div class="floatlabel-wrapper" style="position:relative">
                                    <label class="label-floatlabel red-label" for="valor_ipi" style="position: absolute; top: 0px; left: 8px; display: none; opacity: 0; font-size: 10px; font-weight: bold; z-index: 3; color: rgb(131, 135, 128); transition: all 0.1s ease-in-out 0s;">Valor Total</label>
                                    <input id="valor_ipi-0" onblur="calcularValorTotalIpi(0);" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor IPI" data-class="red-label" placeholder="IPI" name="itens[0][valor_ipi]" style="padding-top: 6px; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                </div>
                                <span class="info clearfix"> </span>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <?php if (!isset($this->ocultarSubmit)) { ?>
                    <div class="panel-footer text-right">
                        <?php
                        if (array_key_exists('botao2', $this->form->getElements()))
                            echo $this->formRow($this->form->get('botao2'));
                        if (array_key_exists('adicionar', $this->form->getElements()))
                            echo $this->formRow($this->form->get('adicionar'));
                        if (array_key_exists('cancelar2', $this->form->getElements()))
                            echo $this->formRow($this->form->get('cancelar2'));
                        if (array_key_exists('cancelar', $this->form->getElements()))
                            echo $this->formButton($this->form->get('cancelar'));
                        ?>
                        <?php $submitbutton = isset($this->btnSubmit) ? "$this->btnSubmit" : "Salvar" ?>
                        <button id="submitbutton" type="button" class="btn btn-primary"><?= $submitbutton; ?></button>
                    </div>
                    <?php if (isset($this->extraButtons)) { ?>
                        <div class="panel-footer text-left">
                            <?php
                            if (array_key_exists('exportarpva', $this->form->getElements())) {
                                echo $this->formButton($this->form->get('exportarpva'));
                            }
                            if (array_key_exists('exportarnfe', $this->form->getElements())) {
                                echo $this->formButton($this->form->get('exportarnfe'));
                            }
                            ?>
                        </div>
                    <?php } ?>

                <?php } ?>
                <?php echo $this->form()->closeTag($this->form); ?>
                <!--===================================================-->
                <!-- END OF BLOCK STYLED FORM FORM  -->
            </div>
        </div>
    </div>
</div>
<!-- MAIN PLUGIN -->
<!-- ================================================= -->


<!-- jQuery Version 2.1.1 -->
<script src="/js/jquery-2.1.1.min.js"></script>
<script src="<?php echo BASE_URL ?>/js/floatlabels.js" type="text/javascript"></script>


<!-- Admin Core -->
</div>
<script src="/js/nifty.min.js"></script>
<script src="/js/demo/form-wizard.js"></script>
<script src="<?php echo BASE_URL ?>/js/floatlabels.js" type="text/javascript"></script>
<?php if (!empty($messageError)) { ?>
    <script>
        $.niftyNoty({
            type: 'danger',
            icon: 'fa fa-bolt fa-2x',
            container: 'page',
            title: 'Foram encontrados problemas no formulário!',
            message: 'Verifique abaixo os campos com avisos, corrija-os e tente novamente.'
        });
    </script>
<?php } $id_processo = $this->session()->offsetGet('processo'); ?>

<script type="text/javascript">
    $('input.floatlabel').floatlabel();
</script>
<script type="text/javascript">
    function mostrarModals() {
        var processo;
        var etapa;
        $JQuery(function () {
            $.ajax({
                type: 'POST',
                url: '<?php echo BASE_URL ?>/main/processo-apuracao/etapa-processo',
                data: {'id': <?php echo $id_processo ?>},
                dataType: 'JSON',
                async: false,
                success: function (d) {
                    etapas(d);
                }
            });
            $('#dialog-new').modal('toggle');
            $JQuery("#titulo-modal").replaceWith('<h4 class="modal-title" id="titulo-modal"><b>Etapas do processo:</b> <?= $modal ?></h4>');
        });
    }
    ;
    function etapas(d) {
        $JQuery('#importacao').removeClass();
        $JQuery('#importacao').addClass(d.importacao.classe);
        $JQuery('#importaxml').removeClass();
        $JQuery('#importaxml').addClass(d.nfe.classe);
        if (d.nfe.block !== '') {
            $JQuery('#importaxml').css('pointer-events', 'none');
        } else {
            $JQuery('#importaxml').css('pointer-events', '');
        }
        $JQuery('#importacte').removeClass();
        $JQuery('#importacte').addClass(d.cte.classe);
        if (d.cte.block !== '') {
            $JQuery('#importacte').css('pointer-events', '');
            $JQuery('#importacte').css('pointer-events', 'none');
        } else {
            $JQuery('#importacte').css('pointer-events', '');
        }
        $JQuery('#conciliacao').removeClass();
        $JQuery('#conciliacao').addClass(d.conciliacao.classe);
        if (d.conciliacao.block !== '') {
            $JQuery('#conciliacao').css('pointer-events', 'none');
        } else {
            $JQuery('#concilaicao').css('pointer-events', '');
        }
        $JQuery('#regras').removeClass();
        $JQuery('#regras').addClass(d.regras.classe);
        if (d.regras.block !== '') {
            $JQuery('#regras').css('pointer-events', 'none');
        } else {
            $JQuery('#regras').css('pointer-events', '');
        }
        $JQuery('#apuracaosped').removeClass();
        $JQuery('#apuracaosped').addClass(d.apuracao.classe);
        if (d.apuracao.block !== '') {
            $JQuery('#apuracao').css('pointer-events', 'none');
        } else {
            $JQuery('#apuracao').css('pointer-events', '');
        }
        $JQuery('#exportar').removeClass();
        $JQuery('#exportar').addClass(d.exportacao.classe);
        if (d.exportacao.block !== '') {
            $JQuery('#exportar').css('pointer-events', 'none');
        } else {
            $JQuery('#exportar').css('pointer-events', '');
        }
    }

    function importar() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importar/save/id/<?php echo $id_processo ?>');
    }
    ;
    function importaxml() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarxml/index/id/<?php echo $id_processo ?>');
    }
    ;
    function importacte() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarcte/index/id/<?php echo $id_processo ?>');
    }
    ;
    function apuracao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/apuracao/index/id/<?php echo $id_processo ?>');
    }
    ;
    function encerrar() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/encerramento/id/<?php echo $id_processo ?>');
        }
    }
    ;
    function exportar() {
        window.location.assign('<?= BASE_URL; ?>' + '/exportacao/exportar-xls/export/id/<?php echo $id_processo ?>');
    }
    ;
    function regras() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/regrasprocesso/index/id/<?php echo $id_processo ?>');
    }
    ;
    function remover() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/delete/id/<?php echo $id_processo ?>');
        }
    }
    ;
    function conciliacao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/conciliacao/index/id/<?php echo $id_processo ?>');
    }
    ;
</script>
<div id="dialog-new-obs" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop fade in"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:63em">
            <div class="modal-header">
                <button id="fechar" class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title text-center" id="titulo-modal"><strong>Informações Complementares</strong></h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body">
                    <div class="div-input-modal">
                        <form id="obs" enctype="multipart/form-data" name="obs" method="post" action="<?= BASE_URL ?>/compras/compra/obs/id/<?= $id ?>">
                            <div class="row">
                                <?php
                                $cont = 0;
                                foreach ($this->partialElements as $chave => $element) {
                                    if (isset($element['id_div'])) {
                                        $idDiv = 'id="' . $element['id_div'] . '"';
                                    } else {
                                        $idDiv = '';
                                    }
                                    if (isset($element['htmlElement'])) {
                                        $html = '<div>' . $element['htmlElement'] . '</div>';
                                    } else {
                                        $html = '';
                                    }
                                    if (isset($element['grupo']) && $element['grupo'] == 'obs') {
                                        ?>
                                        <?php if ($cont == 0) { ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                    <?php
                                                    if (!isset($element['none'])) {
                                                        if (isset($element['label']) && !isset($element['icon'])) {
                                                            echo $element['label'];
                                                        } else {
                                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                                ?>
                                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                                                        </span>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                    <?php
                                                    if (isset($element['calendario'])) {
                                                        ?>
                                                        <div id="demo-dp-txtinput">
                                                            <?php echo $element['input'] ?>
                                                        </div>
                                                    <?php
                                                    } else if (!isset($element['type'])) {
                                                        echo $element['input'];
                                                        if (isset($messageError[$element['name']])) {
                                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                                            echo $errorIcon;
                                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                        }
                                                    } else {
                                                        ?>
                                                        <br>
                                                        <span class="btn btn-default btn-file">
                                                                    <?php
                                                                    echo $element['label'];
                                                                    echo $element['input'];
                                                                    ?>
                                                                </span>
                                                    <?php } ?>
                                                    <span class="info clearfix">
                                                                <?php
                                                                if (isset($element['information']))
                                                                    echo $element['information'];
                                                                else if (isset($element['information2']))
                                                                    echo $element['information'];
                                                                ?>
                                                            </span>
                                                </div>
                                            </div>
                                            <?php
                                            $cont = 1;
                                        } else {
                                            ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                    <?php
                                                    if (!isset($element['none'])) {
                                                        if (isset($element['label']) && !isset($element['icon'])) {
                                                            echo $element['label'];
                                                        } else {
                                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                                ?>
                                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                                                        </span>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                    <?php
                                                    if (isset($element['calendario'])) {
                                                        ?>
                                                        <div id="demo-dp-txtinput">
                                                            <?php echo $element['input'] ?>
                                                        </div>
                                                    <?php
                                                    } else if (!isset($element['type'])) {
                                                        echo $element['input'];

                                                        if (isset($messageError[$element['name']])) {
                                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                                            echo $errorIcon;
                                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                        }
                                                    } else {
                                                        ?>
                                                        <br>

                                                        <span class="btn btn-default btn-file">
                                                                    <?php
                                                                    echo $element['label'];
                                                                    echo $element['input'];
                                                                    ?>
                                                                </span>
                                                    <?php } ?>
                                                    <span class="info clearfix">
                                                                <?php
                                                                if (isset($element['information']))
                                                                    echo $element['information'];
                                                                else if (isset($element['information2']))
                                                                    echo $element['information'];
                                                                ?>
                                                            </span>

                                                </div>
                                                <?php echo $html; ?>
                                            </div>
                                            <?php
                                            $cont = 0;
                                        }
                                    }
                                }
                                ?>
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="text-right" style="margin-top:5px;">
                    <button type="button" id="btnsubmitobs" class="btn btn-primary" aria-hidden="true" data-dismiss="modal" onclick="salvarModal('obs');">Salvar</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<div id="dialog-new-transp" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop fade in"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:63em">
            <div class="modal-header">
                <button id="fechar" class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title text-center" id="titulo-modal"><strong>Informações Complementares</strong></h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body">
                    <div class="div-input-modal">
                        <form id="transp" enctype="multipart/form-data" name="transp" method="post" action="<?= BASE_URL ?>/compras/compra/transp/id/<?= $id ?>">
                            <div class="row">
                                <?php
                                $cont = 0;
                                if (isset($upperCheckbox)) {
                                    foreach ($upperCheckbox as $elementos) {
                                        foreach ($elementos as $chave => $element) { ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <label class="control-label" style="margin-left: 12%">
                                                    <?= $element['label'] ?>
                                                </label>
                                                <div class="radio">
                                                    <?php foreach($element['values'] as $key => $val) { ?>
                                                        <label class="form-radio form-icon">
                                                            <input name="<?= $element['name'] ?>" id="<?= $element['id'].'-'.$key ?>" value="<?= $key ?>" type="radio">
                                                            <?php echo $val; ?>
                                                        </label>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        <?php
                                        }
                                    }
                                }
                                foreach ($this->partialElements as $chave => $element) {
                                    if (isset($element['id_div'])) {
                                        $idDiv = 'id="' . $element['id_div'] . '"';
                                    } else {
                                        $idDiv = '';
                                    }
                                    if (isset($element['htmlElement'])) {
                                        $html = '<div>' . $element['htmlElement'] . '</div>';
                                    } else {
                                        $html = '';
                                    }
                                    if (isset($element['grupo']) && $element['grupo'] == 'transp') {
                                        ?>
                                        <?php if ($cont == 0) { ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                    <?php
                                                    if (!isset($element['none'])) {
                                                        if (isset($element['label']) && !isset($element['icon'])) {
                                                            echo $element['label'];
                                                        } else {
                                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                                ?>
                                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                                                        </span>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                    <?php
                                                    if (isset($element['calendario'])) {
                                                        ?>
                                                        <div id="demo-dp-txtinput">
                                                            <?php echo $element['input'] ?>
                                                        </div>
                                                    <?php
                                                    } else if (!isset($element['type'])) {
                                                        echo $element['input'];
                                                        if (isset($messageError[$element['name']])) {
                                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                                            echo $errorIcon;
                                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                        }
                                                    } else {
                                                        ?>
                                                        <br>
                                                        <span class="btn btn-default btn-file">
                                                                    <?php
                                                                    echo $element['label'];
                                                                    echo $element['input'];
                                                                    ?>
                                                                </span>
                                                    <?php } ?>
                                                    <span class="info clearfix">
                                                                <?php
                                                                if (isset($element['information']))
                                                                    echo $element['information'];
                                                                else if (isset($element['information2']))
                                                                    echo $element['information'];
                                                                ?>
                                                            </span>
                                                </div>
                                            </div>
                                            <?php
                                            $cont = 1;
                                        } else {
                                            ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                    <?php
                                                    if (!isset($element['none'])) {
                                                        if (isset($element['label']) && !isset($element['icon'])) {
                                                            echo $element['label'];
                                                        } else {
                                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                                ?>
                                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                                                        </span>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                    <?php
                                                    if (isset($element['calendario'])) {
                                                        ?>
                                                        <div id="demo-dp-txtinput">
                                                            <?php echo $element['input'] ?>
                                                        </div>
                                                    <?php
                                                    } else if (!isset($element['type'])) {
                                                        echo $element['input'];

                                                        if (isset($messageError[$element['name']])) {
                                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                                            echo $errorIcon;
                                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                        }
                                                    } else {
                                                        ?>
                                                        <br>

                                                        <span class="btn btn-default btn-file">
                                                                    <?php
                                                                    echo $element['label'];
                                                                    echo $element['input'];
                                                                    ?>
                                                                </span>
                                                    <?php } ?>
                                                    <span class="info clearfix">
                                                                <?php
                                                                if (isset($element['information']))
                                                                    echo $element['information'];
                                                                else if (isset($element['information2']))
                                                                    echo $element['information'];
                                                                ?>
                                                            </span>

                                                </div>
                                                <?php echo $html; ?>
                                            </div>
                                            <?php
                                            $cont = 0;
                                        }
                                    }
                                }
                                ?>
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="text-right" style="margin-top:5px;">
                    <button type="button" id="btnsubmittrans" class="btn btn-primary" aria-hidden="true" data-dismiss="modal" onclick="salvarModal('transp');">Salvar</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<div id="dialog-new-modals" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop fade in"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:63em">
            <div class="modal-header">
                <button id="fechar" class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title text-center" id="titulo-modal"><strong><?= $titulo ?> Não Cadastrado(a) - Deseja salvá-lo(a)?</strong></h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body">
                    <div class="div-input-modal">
                        <form id="mod" enctype="multipart/form-data" name="mod" method="post" action="">
                            <div class="row">
                                <?php
                                $cont = 0;
                                foreach ($this->partialElements as $chave => $element) {
                                    if (isset($element['id_div'])) {
                                        $idDiv = 'id="' . $element['id_div'] . '"';
                                    } else {
                                        $idDiv = '';
                                    }
                                    if (isset($element['htmlElement'])) {
                                        $html = '<div>' . $element['htmlElement'] . '</div>';
                                    } else {
                                        $html = '';
                                    }
                                    if (isset($element['grupo']) && $element['grupo'] == 'cad') {
                                        ?>
                                        <?php if ($cont == 0) { ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                    <?php
                                                    if (!isset($element['none'])) {
                                                        if (isset($element['label']) && !isset($element['icon'])) {
                                                            echo $element['label'];
                                                        } else {
                                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                                ?>
                                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                                                        </span>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                    <?php
                                                    if (isset($element['calendario'])) {
                                                        ?>
                                                        <div id="demo-dp-txtinput">
                                                            <?php echo $element['input'] ?>
                                                        </div>
                                                    <?php
                                                    } else if (!isset($element['type'])) {
                                                        echo $element['input'];
                                                        if (isset($messageError[$element['name']])) {
                                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                                            echo $errorIcon;
                                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                        }
                                                    } else {
                                                        ?>
                                                        <br>
                                                        <span class="btn btn-default btn-file">
                                                                    <?php
                                                                    echo $element['label'];
                                                                    echo $element['input'];
                                                                    ?>
                                                                </span>
                                                    <?php } ?>
                                                    <span class="info clearfix">
                                                                <?php
                                                                if (isset($element['information']))
                                                                    echo $element['information'];
                                                                else if (isset($element['information2']))
                                                                    echo $element['information'];
                                                                ?>
                                                            </span>
                                                </div>
                                            </div>
                                            <?php
                                            $cont = 1;
                                        } else {
                                            ?>
                                            <div class="col-sm-6" style="margin-top: 10px;">
                                                <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                                    <?php
                                                    if (!isset($element['none'])) {
                                                        if (isset($element['label']) && !isset($element['icon'])) {
                                                            echo $element['label'];
                                                        } else {
                                                            if (isset($element['icon']) && isset($element['nome'])) {
                                                                ?>
                                                                <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                                                        </span>
                                                            <?php
                                                            }
                                                        }
                                                    }
                                                    ?>
                                                    <?php
                                                    if (isset($element['calendario'])) {
                                                        ?>
                                                        <div id="demo-dp-txtinput">
                                                            <?php echo $element['input'] ?>
                                                        </div>
                                                    <?php
                                                    } else if (!isset($element['type'])) {
                                                        echo $element['input'];

                                                        if (isset($messageError[$element['name']])) {
                                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                                            echo $errorIcon;
                                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                        }
                                                    } else {
                                                        ?>
                                                        <br>

                                                        <span class="btn btn-default btn-file">
                                                                    <?php
                                                                    echo $element['label'];
                                                                    echo $element['input'];
                                                                    ?>
                                                                </span>
                                                    <?php } ?>
                                                    <span class="info clearfix">
                                                                <?php
                                                                if (isset($element['information']))
                                                                    echo $element['information'];
                                                                else if (isset($element['information2']))
                                                                    echo $element['information'];
                                                                ?>
                                                            </span>

                                                </div>
                                                <?php echo $html; ?>
                                            </div>
                                            <?php
                                            $cont = 0;
                                        }
                                    }
                                }
                                ?>
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="text-right" style="margin-top:5px;">
                    <button type="button" id="btnsubmittrans" class="btn btn-primary" aria-hidden="true" data-dismiss="modal" onclick="salvarPessoa();">Salvar</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<div id="dialog-new-provisionado" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px" aria-hidden="false">
    <div class="modal-backdrop fade in"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:180%; height:20%; margin-left: -36%">
            <div class="modal-header">
                <button id="fechar" class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title text-center" id="titulo-modal"><strong>Há titulos provisionados semelhantes a nota importada.</strong></h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body">
                    <div class="div-input-modal">
                        <?php $cabecalho = $this->cabecalho; ?>
                        <?php if($cabecalho != null) { ?>
                            <div id="cabecalho" class="div-input-modal" style="border: 1px solid #000000; margin: 1%; background-color: #DCDCDC;">
                                <table style="width: 100%">
                                    <tbody>
                                    <tr>
                                        <td colspan="2"><span style="margin-left: 1.5%"><strong>Empresa do Grupo: </strong><?= $cabecalho->empresa_grupo->id->nome ?></span></td>
                                    </tr>
                                    <tr>
                                        <td colspan="2"><span style="margin-left: 1.5%"><strong>Fornecedor: </strong><?= $cabecalho->fornecedor_cliente->nome ?></span></td>
                                    </tr>
                                    <tr>
                                        <td><span style="margin-left: 3%"><strong>Número da Nota: </strong><?= $cabecalho->numero_nfe ?></span></td>
                                        <td><span style="margin-left: 5%"><strong>Série da Nota: </strong><?= $cabecalho->serie_nfe ?></span></td>
                                    </tr>
                                    <tr>
                                        <td><span style="margin-left: 3%"><strong>Valor Total: </strong><?= number_format($cabecalho->valor_total, 2, ',', '.') ?></span></td>
                                        <td><span style="margin-left: 5%"><strong>Data Emissão: </strong><?= $cabecalho->data_emissao->format('d/m/Y') ?></span></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        <?php } ?>
                        <form id="mod" enctype="multipart/form-data" name="mod" method="post" action="">
                            <div class="row">
                                <div class="col-sm-12">
                                    <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-click-to-select="true">
                                        <thead id="cabecalho">
                                        <tr>
                                            <?php
                                            if (isset($this->tableInformation))
                                                foreach ($this->tableInformation as $th) {
                                                    if ($th['index'] == 'checkbox') {
                                                        ?>
                                                        <th data-align="center" data-sortable="false" data-checkbox="true"></th><?php } else { ?>
                                                        <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php
                                                        if (isset($th['events'])) {
                                                            echo $th['events'];
                                                        }
                                                        ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
                                                    <?php
                                                    }
                                                }
                                            ?>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="text-right" style="margin-top:5px;">
                    <span style="float: left;">Selecione o checkbox e click em salvar para vincular a nota ao titulo provisionado.</span>
                    <button type="button" id="btncancelprov" class="btn btn-danger" aria-hidden="true" data-dismiss="modal" onclick="salvarProvisionado('cancel')">Cancelar</button>
                    <button type="button" id="btnsubmitprov" class="btn btn-primary" aria-hidden="true" data-dismiss="modal" onclick="salvarProvisionado('submit')">Salvar</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>