<!-- ##### BREADCRUMBS #####-->
<?php
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        $split = explode('/', $this->breadcrumbs[$endKey]['url']);
        $programa = $split[2];
        $acao = $split[3];
        $pagorecebido = $programa == 'contasapagar' ? 'Pago' : 'Recebido';
        $pagarreceber = $programa == 'contasapagar' ? 'pagar' : 'receber';
        $pagarecebemento = $programa == 'contasapagar' ? 'pagamento' : 'recebimento';
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else {
                    ?>
                    <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
                    <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<input id="demo-sw-checkstate" type="hidden">
<input id="demo-sw-checkstate-field"  type="hidden">

<div id="page-content">
    <?php
    echo $this->form()->openTag($this->form);
    $messageError = $this->form->getMessages();
    $classError = 'has-error has-feedback';
    $errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
    ?>
    <?php if ($acao != 'save') { //---------------------- INDEX ------------------------?>
        <div class="panel">
            <div class="panel-body" style="width:70%;">
                <div class="row" style="border:2px solid black; background-color: #dcdcdc; margin-left: 15px;">
                    <?php
                    if (isset($this->display)) {
                        foreach ($this->display as $key => $d) {
                            ?>
                            <?php $float = $key < 4 ? 'left' : 'right'; ?>
                            <div class="col-md-6">
                                <h4><?= $d['index']; ?><span id=<?= $d['color']; ?>> <?= $d['value']; ?></span></h4>
                            </div>
                            <?php
                        }
                    }
                    ?>
                    <div id="pizza" style="width:400px; height:230px; margin-left: 105%;"></div>
                </div>
            </div>
        </div>
        <div class="panel">
            <?php if (isset($this->help)) { ?>
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->help ?></h3>
                </div>
            <?php } ?>
            <div class="panel-body">
                <select id="filtrar" class="chosen-select label label-info form-control" data-label='Filtros' name="filtrar" style="display: none;">
                    <option value="0">Filtrar</option>
                    <option value="1">Contas a <?= $pagarreceber; ?></option>
                    <option value="2"><?= $pagorecebido; ?>s</option>
                    <option value="3">Todos</option>
                </select>
                <select id="mostrar" class="chosen-select label label-info form-control" data-label='' name="mostrar" style="display: none;">
                    <option value="0">Mostrar</option>
                    <option value="1">Hoje</option>
                    <option value="2">Esta semana</option>
                    <option value="3">Últimos 30 dias</option>
                    <option value="4">Todos</option>
                </select>
                <input type="button" onclick="aplicarFiltro();" style="margin-left: 1%; margin-top: -1%;"value="Aplicar" class="btn btn-info" id="aplicar"/>
                <div class="bootstrap-table">
                    <?php if (isset($this->newButton)) { ?>
                        <div class="panel-footer text-left">
                            <a style="margin-left: 10px" <?php if (isset($this->newButton['id'])) echo 'id=' . $this->newButton['id'] ?> class="btn btn-lg btn-primary" href='<?php echo $this->newButton['href'] ?>'><?php echo $this->newButton['text'] ?></a>
                        </div>

                    <?php } ?>
                    <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-sort-name="id" data-sort-order="desc" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-click-to-select="false">
                        <thead id="cabecalho">
                            <tr>
                                <?php
                                foreach ($this->tableInformation as $th) {
                                    if ($th['index'] == 'checkbox') {
                                        ?>
                                        <th data-align="center" data-sortable="false" data-checkbox="true"></th><?php } else { ?>
                                        <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php
                                        if (isset($th['events'])) {
                                            echo $th['events'];
                                        }
                                        ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
                                            <?php
                                        }
                                    }
                                    ?>
                            </tr>
                        </thead>
                    </table>
                </div>
                <input type="button" onclick="fn_historicos();" style="" value="Históricos" class="btn btn-primary" id="historicos"/>
                <input type="button" onclick="editarContasBancarias();" style="" value="Editar contas bancárias" class="btn btn-primary" id="editar_contas"/>
                <input type="button" onclick="editarCategorias();" style="" value="Editar categorias" class="btn btn-primary" id="editar_categorias"/>
                <div class="clearfix"></div>
            </div>
        </div>
    <?php } else if ($acao == 'save') { //---------------------- SAVE ------------------------------?> 
        <div class="panel">
            <?php if (isset($this->help)) { ?>
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->help ?></h3>
                </div>
            <?php } ?>
            <div class="panel-body">
                <?php
                $total = count($this->partialElements);
                $contcheck = 0;
                foreach ($this->partialElements as $chave => $element) {
                    $contcheck++;
                    if (isset($element['id_div'])) {
                        $idDiv = 'id="' . $element['id_div'] . '"';
                    } else {
                        $idDiv = '';
                    }
                    if (isset($element['htmlElement'])) {
                        $html = '<div>' . $element['htmlElement'] . '</div>';
                    } else {
                        $html = '';
                    }
                    ?>
                    <?php
                    if (!isset($element['colunas'])) {
                        if ($element['name'] == 'fornecedor' || $element['name'] == 'empresa_grupo') {
//                         $this->colunas = 3; 
                            ?>
                            <!--<div class="col-sm-3" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">-->
                                <!--<label class="form-checkbox form-icon">-->
                                <!--<input type="button" onclick="lote();" style="float:right; margin-left: 20px; margin-bottom: 5px;" value="Nº Lote" class="btn btn-primary" id="historicos"/>-->
                                <!--</label>-->
                            <!--</div>-->
                            <div class="col-sm-10" style="margin-top: 15px; max-height: 45px; margin-bottom: -5px;">
                                <label id="provisionado" class="form-checkbox form-icon">
                                    <input id="provisionado" type="checkbox" value="0" name="provisionado">
                                    Provisionado
                                </label>
                                <?php if ($element['name'] == 'valor_contribuinte') { ?>
                                    <input type="button" onclick="historicos();" style="float:right; margin-left: 20px; margin-bottom: 5px;" value="Históricos" class="btn btn-primary" id="historicos"/>
                                <?php } ?>
                                <hr style='width: 122%; margin-top: 10px; padding-bottom: 10px;'>
                            </div>
                            <?php
                        } ?>   
                        <div class="col-sm-<?= $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                        <?php } ?>
                        <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                            <?php
                            if (!isset($element['none'])) {
                                if (isset($element['label']) && !isset($element['icon'])) {
                                    echo $element['label'];
                                } else {
                                    if (isset($element['icon']) && isset($element['nome'])) {
                                        ?>
                                        <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                        </span>
                                        <?php
                                    }
                                }
                            }
                            ?>
                            <?php
                            if (isset($element['calendario'])) {
                                ?>
                                <div id="demo-dp-txtinput">
                                    <?php echo $element['input'] ?>
                                </div>
                                <?php
                            } else if (!isset($element['type'])) {
                                echo $element['input'];
                                if (isset($messageError[$element['name']])) {
                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                    echo $errorIcon;
                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                }
                            } else {
                                ?>
                                <br>
                                <span class="btn btn-default btn-file">
                                    <?php
                                    echo $element['label'];
                                    echo $element['input'];
                                    ?>
                                </span>
                            <?php } ?>
                            <span class="info clearfix"></span>
                        </div>
                    </div>
                    <?php if ($total == $contcheck) { ?>

                        <div class="col-sm-10" style="margin-top: 15px; max-height: 45px; margin-bottom: 5px;">
                            <hr style="width: 122%"/>
                            <input type="button" class="btn btn-primary" value="Repetir parcelas" name="repetir" onclick="repetirParcelaModal()">
                        </div>
                        <div  class="col-sm-10" style="margin-top: 15px; max-height: 45px; margin-bottom: -5px;">
                            <hr style="width: 122%"/>
                            <input type="button" disabled="disabled" class="btn btn-primary" value="Realizar <?php echo $pagarecebemento ?>" name="<?php echo $pagarecebemento ?>" onclick="recebimentoModal()">
                        </div>
                        <div class="col-sm-12" style="margin-top: 30px; max-height: 45px; margin-bottom: -15px;">
                            <input type="button" onclick="save(null);" style="float:right; margin-left: 10px; margin-bottom: 5px;" value="Salvar" class="btn btn-primary" id="salvar"/>
                            <input type="button" onclick="fn_voltar();" style="float:right; margin-left: 20px; margin-bottom: 5px;" value="Cancelar" class="btn btn-danger" id="voltar"/>
                        </div>

                    <?php } ?>
                <?php } ?>     
            </div>
        </div>

        <aside id="aside-container">
            <div id="aside">
                <div class="nano">
                    <div class="nano-content" id='menu_email'>
                        <div class="pad-hor">
                            <h4 class="text-thin"><?= $tela ?></h4>
                            <form id="form-aside" class="form-group-sm" method="POST">
                                <!--Valor Bruto-->
                                <!--                            <div class="input-group mar-btm">
                                                                <span class="input-group-addon badge-default" title="Valor Bruto">
                                                                    <i class="fa fa-dollar fa-lg"></i>
                                                                </span>  
                                                                <input id='valor_bruto' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor Bruto" data-class="red-label" placeholder="Valor Bruto" name="valor_bruto" data-original-title="" title="">
                                                            </div>-->
                                <!--Valor IRFF-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor IRFF">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_irrf' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor IRFF" data-class="red-label" placeholder="Valor IRFF" name="valor_irrf" data-original-title="" title="">
                                </div>
                                <!--Valor PIS-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor PIS">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_pis' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor PIS" data-class="red-label" placeholder="Valor PIS" name="valor_pis" data-original-title="" title="">
                                </div>
                                <!--Valor COFINS-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor COFINS">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_cofins' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor COFINS" data-class="red-label" placeholder="Valor COFINS" name="valor_cofins" data-original-title="" title="">
                                </div>
                                <!--Valor CSII-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor CSII">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_csll' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor CSII" data-class="red-label" placeholder="Valor CSII" name="valor_csll" data-original-title="" title="">
                                </div>
                                <!--Valor INSS-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor INSS">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_inss' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor INSS" data-class="red-label" placeholder="Valor INSS" name="valor_inss" data-original-title="" title="">
                                </div>
                                <!--Valor ISS-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor ISS">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_iss' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor ISS" data-class="red-label" placeholder="Valor ISS" name="valor_iss" data-original-title="" title="">
                                </div>
                                <!--Valor Título-->
                                <div class="input-group mar-btm">
                                    <span class="input-group-addon badge-default" title="Valor Título">
                                        <i class="fa fa-dollar fa-lg"></i>
                                    </span>  
                                    <input id='valor_titulo' readonly="true" disabled="true" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor Título" data-class="red-label" placeholder="Valor Título" name="valor_titulo" data-original-title="" title="">
                                </div>
                        </div>
                        <hr>
                        <div class="pad-hor">
                            <!--Observações-->
                            <div class="input-group mar-btm">
                                <span class="input-group-addon badge-default" title="Observações">
                                    <i class="fa fa-comment-o fa-lg"></i>
                                </span>  
                                <input id='observacao' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Observações" data-class="red-label" placeholder="Observações" name="observacao" data-original-title="" title="">
                            </div>
                        </div>
                        <hr>
                        <!--                    <div class="pad-hor">
                                                <a href="<?php // echo BASE_URL . "/financeiro/" . $programa . "/save"      ?>" class="btn btn-block btn-info">
                                                    Salvar
                                                </a>
                                            </div>-->
                        <!--<hr>-->
                        </form>
                    </div>
                </div>
            </div>
            </aside>
        <?php } ?>
</div>
<script src="<?php echo BASE_URL ?>/js/jquery.maskMoney.min.js" type="text/javascript"></script> 
<script src="<?php echo BASE_URL ?>/js/jquery.flot.min.js" type="text/javascript"></script>   
<script src="<?php echo BASE_URL ?>/js/jquery.flot.pie.min.js" type="text/javascript"></script>   
<script src="<?php echo BASE_URL ?>/js/floatlabels.js" type="text/javascript"></script> 
<script type="text/javascript">
$JQuery(function() {
$JQuery('[name="refresh"]').click(function() {
var aux = window.location.pathname;
        $('#demo-table').bootstrapTable('refresh', {url: aux});
});
});
function downloadExportFormatter(value, row) {
if (value)
{
if (value == "Em andamento...") {
return value;
}
else
        return '<a href="<?= BASE_URL; ?>/exportacao/exportar-xls/file/id/' + JSON.stringify(row.id) + '" class="btn-link"  title="Download do arquivo"> ' + value + '</a>';
}
return '-';
}
function statusRegra(value, row){
if (value === '1'){
return '<i class="fa fa-check fa-2x"></i> ';
} else {
return '<i class="fa fa-spin fa-spinner fa-pulse fa-2x"></i> ';
}
}
function gridFormatter(value, row){
if (value)
        return '<a href="<?php echo $this->addIcon[0]['url']; ?>/table/' + row.table_name + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
}
function nameFormatter(value, row) {
if (value)
        return '<a href="<?php echo $this->addIcon[0]['url']; ?>/id/' + JSON.stringify(row.id) + "/id_recpag/" + row.id_recpag + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
}
function nameFormatterTxt(value, row) {
if (value)
        return '<a href="<?php echo $this->addIcon[0]['url']; ?>/txt/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
}


<?php if (isset($this->addIcon)) { ?>
                        function operateFormatter(value, row, index) {
                        return [
    <?php
    foreach ($this->addIcon as $item) {
        if (isset($item['onClick'])) {
            ?>
                                '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" onclick="<?php echo $item['onClick'] ?>" title="<?php echo $item['title']; ?>">',
        <?php } else { ?>
                                '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" title="<?php echo $item['title']; ?>">',
        <?php } ?>
                            '<i class="<?php echo $item['classButton']; ?>"></i>',
                                    '</a>&nbsp;&nbsp;&nbsp;',
    <?php } ?>
                        ].join('');
                        } <?php } ?>

<?php if (isset($this->addIcon)) { ?>
                        window.operateEvents = {
    <?php
    foreach ($this->addIcon as $item) {
        if ($item['classHref'] == 'remove') {
            ?>
                                'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
                                if (confirm('Deseja deletar este registro?') == true){
                                window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                                }
                                },
        <?php } else { ?>
                                'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
                                    alert();
                                window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
                                },
        <?php } ?>
    <?php } ?>
                        };
<?php } ?>


<?php if ($acao == 'index') { ?>
                        var dataSet = [];
    <?php
    //
//    if (isset($this->display)) {
//        $i = 0;
//        foreach ($this->display as $key => $d) {
//            if ($i < 4) {
//                $i++;
//                
    ?>
                        //                dataSet.push({label: '<?= str_replace('R$', '%', $d['index']) ?>', data: '<?= $d['value'] ?>', color: '<?= $d['color'] ?>'});
    <?php
//            }
//        }
//    }
    ?>

                        //                                        $JQuery.plot('#pizza', dataSet, {
                        //                                        series: {
                        //                                        pie: {
                        //                                        show: true,
                        //                                                combine: {
                        //                                                color: '#999',
                        //                                                        threshold: 0.1
                        //                                                }
                        //                                        }},
                        //                                                legend: {
                        //                                                show: false
                        //                                                }});
<?php } ?>
</script>
<div id="dialog-new-repetir" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop fade in" style="height: 1049px;"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:63em">
            <div class="modal-header">
                <button class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title" id="titulo-modal">Repetir <?= $tela ?></h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body">      
                    <div class="div-input-modal">
                        <div id="cabecalho" class="div-input-modal" style="border: 1px solid #000000; margin: 1%; background-color: #DCDCDC;">
                            <table style="width: 100%">
                                <tbody>
                                    <tr>
                                        <td><strong>Empresa: </strong><span id='empresa_grupo_span'></span></td>
                                        <td><strong>Descrição: </strong><span id='descricao_lancamento_span'></span></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Valor titulo: </strong><span id='valor_span'></span></td>
                                        <td><strong>Data de vencimento: </strong><span id='data_vencimento_span'></span></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <hr>
                        <?php // }  ?>
                        <form id="form-modal" method="POST" action="modal" enctype='multipart/form-data'>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group mar-btm">
                                        <span class="input-group-addon badge-default" title="Periodicidade">
                                            <i class="fa fa-calendar fa-lg"></i>
                                        </span>  
                                        <select id="periodicidade" class="chosen-select label label-info form-control" data-label='' name="periodicidade" style="display: none;">
                                            <option value="1">MENSALMENTE</option>
                                            <option value="2">DIARIAMENTE</option>
                                            <option value="3">TRIMESTRALMENTE</option>
                                            <option value="4">SEMESTRALMENTE</option>
                                            <option value="5">ANUALMENTE</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group mar-btm">
                                        <span class="input-group-addon badge-default" title="Numero">
                                            <i class="fa fa-list fa-lg"></i>
                                        </span>  
                                        <input id='numero' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Numero" data-class="red-label" placeholder="Numero" name="numero" data-original-title="" title="">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group mar-btm">
                                        <span class="input-group-addon badge-default" title="Descrição lançamento">
                                            <i class="fa fa-comment-o fa-lg"></i>
                                        </span>  
                                        <input id='desc_lancamento' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Descrição lançamento" data-class="red-label" placeholder="Descrição lançamento" name="desc_lancamento" data-original-title="" title="">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group mar-btm">
                                        <span class="input-group-addon badge-default" title="Valor Parcela">
                                            <i class="fa fa-dollar fa-lg"></i>
                                        </span>  
                                        <input id='valor_parcela' class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor Parcela" data-class="red-label" placeholder="Valor Parcela" name="valor_parcela" data-original-title="" title="">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-7">
                                    <label class="form-checkbox form-icon">
                                        <input id="parcela_provisionado" type="checkbox" value="0" name="parecela_provisionado[]">
                                        Provisionado
                                    </label>
                                </div>
                                <div class="col-sm-3">
                                    <a href="#" onclick="adicionarParcela();" class="btn btn-block btn-info">
                                        Adicicionar Parcela
                                    </a>
                                </div>
                                <div class="col-sm-2">
                                    <small>Subtotal:</small><span id="subtotal"> 0.00</span>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            </form>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<div id="dialog-new-lotes" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop fade in" style="height: 1049px;"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:63em">
            <div class="modal-header">
                <button class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title" id="titulo-modal"><strong>Lote Nº:  <span id="numero_lote"></span></strong></h4>
            </div>
            <div class="modal-body">
                <ul id="lista_lote">
                </ul>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<div id="dialog-new-pagamento" class="bootbox modal fade in" role="dialog" tabindex="-1" style="display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop" style="height: 1049px;"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:63em">
            <div class="modal-header">
                <button class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title" id="titulo-modal"><strong>Pagar titulo <span id="numero_lote"></span></strong></h4>
            </div>
            <div class="modal-body">
                <div id="cabecalho" class="div-input-modal" style="border: 1px solid #000000; margin: 1%; background-color: #DCDCDC;">
                    <table style="width: 100%">
                        <tbody>
                            <tr>
                                <td><strong>Empresa: </strong><span id='empresa_grupo_span' style="margin-left: 3%"></span></td>
                                <td><strong>Conta bancária: </strong><span id='conta_bancaria_span' style="margin-left: 5%"></span></td>
                            </tr>
                            <tr>
                                <td><strong>Descrição: </strong><span id='descricao_span' style="margin-left: 3%"></span></td>
                                <td><strong>Valor titulo: </strong><span id='valor_titulo_span' style="margin-left: 5%"></span></td>
                            </tr>
                            <tr>
                                <td><strong>Categoria: </strong><span id='categoria_span' style="margin-left: 3%"></span></td>
                                <td><strong>Data de vencimento: </strong><span id='data_vencimento_span' style="margin-left: 3%"></span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <hr>
                <form id="form_pagamento" action="" method="POST" name="form_pagamento"> 
                    <div class="row">
                        <div class="col-sm-4" style="margin-top: 40px; max-height: 45px; margin-bottom: 5px;">
                            <div class="input-group mar-btm " id="juros_multa">
                                <span class="input-group-addon" title="Juros/Multa">
                                    <i class="fa fa-dollar fa-lg"></i>
                                </span>
                                <input id="juros_multa" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Juros/Multa" data-class="red-label" placeholder="Juros/Multa" name="juros_multa" data-original-title="" title="">
                                <span class="info clearfix"></span>
                            </div>
                        </div>
                        <div class="col-sm-4" style="margin-top: 40px; max-height: 45px; margin-bottom: 5px;">
                            <div class="input-group mar-btm " id="valor_<?php echo lcfirst($pagorecebido) ?>">
                                <span class="input-group-addon" title="Valor <?php echo lcfirst($pagorecebido) ?>">
                                    <i class="fa fa-dollar fa-lg"></i>
                                </span>
                                <input id="valor_<?php echo lcfirst($pagorecebido) ?>" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Valor <?= lcfirst($pagorecebido) ?>" data-class="red-label" placeholder="Valor <?= lcfirst($pagorecebido) ?>" name="valor_<?= lcfirst($pagorecebido) ?>" data-original-title="" title="">
                                <span class="info clearfix"></span>
                            </div>
                        </div>
                        <div class="col-sm-4" style="margin-top: 40px; max-height: 45px; margin-bottom: 5px;">
                            <div class="input-group mar-btm "id="descontos_taxas">
                                <span class="input-group-addon" title="Descontos/Taxas">
                                    <i class="fa fa-dollar fa-lg"></i>
                                </span>
                                <input id="descontos_taxas" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Descontos/Taxas" data-class="red-label" placeholder="Descontos/Taxas" name="descontos_taxas" data-original-title="" title="">
                                <span class="info clearfix"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6" style="margin-top: 40px; max-height: 45px; margin-bottom: 5px;">
                            <div class="input-group mar-btm " id="data_<?php echo $pagarecebemento ?>">
                                <span class="input-group-addon" title="Data <?php echo $pagarecebemento ?>">
                                    <i class="fa fa-calendar fa-lg"></i>
                                </span>
                                <input id="data_<?php echo $pagarecebemento ?>" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" onblur="validarDatas($JQuery(this));" data-label="Data <?= $pagarecebemento ?>" data-class="red-label" placeholder="Data <?= $pagarecebemento ?>" name="data_<?= $pagarecebemento ?>" data-original-title="" title="">
                                <span class="info clearfix"></span>
                            </div>
                        </div>
                        <div class="col-sm-6" style="margin-top: 40px; max-height: 45px; margin-bottom: 5px;">
                            <div class="input-group mar-btm " id="observacao">
                                <span class="input-group-addon" title="Observação">
                                    <i class="fa fa-dollar fa-lg"></i>
                                </span>
                                <input id="observacao" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Observação" data-class="red-label" placeholder="Observação" name="observacao" data-original-title="" title="">
                                <span class="info clearfix"></span>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <div class="col-sm-12">
                        <input type="button" value="Salvar" class="btn btn-primary" id="salvar_pagamento"/>
                        <input type="button" onclick="voltar();" style="float:right; margin-left: 10px; margin-bottom: 5px;" value="Cancelar" class="btn btn-danger" id="voltar"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="dialog-new-pagrec" class="bootbox modal fade in" role="dialog" tabindex="-1" style="overflow:auto; display: none; padding-right: 13px;" aria-hidden="false">
    <div class="modal-backdrop" style="height: 1049px;"></div>
    <div class="modal-dialog">
        <div class="modal-content" style="width:80em; height: 45em; margin-left: -10em; overflow: auto;">
            <div class="modal-header">
                <button class="bootbox-close-button close" aria-hidden="true" data-dismiss="modal" type="button">×</button>
                <h4 class="modal-title" id="titulo-modal"><?= ucfirst($pagarecebemento); ?> de Título</h4>
            </div>
            <div class="modal-body">
                <div class="bootbox-body" id="modal-body-pagrec"></div>
            </div>
            <div style="height:5em;" class="modal-footer">
                <input type="button" onclick="saveModalPagRec();" style="float:right; margin-left: 10px; margin-bottom: 5px;" value="Salvar" class="btn btn-primary" id="salvar_pagrec"/>
                <input type="button" onclick="fecharModalPagRec();" style="float:right; margin-bottom: 5px;" value="Fechar" class="btn btn-danger" id="voltar_pagrec"/>
            </div>
        </div>
    </div>
</div>