<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php
                } else {
                    if (isset($modal)) {
                        ?>
                        <li><a href="#" title="Opções" onclick="mostrarModals();"><?php echo $modal; ?></a></li>
                    <?php } ?>
                    <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
                <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<div id="page-content">
    <div class="panel">
        <?php if (isset($this->help)) { ?>
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->help ?></h3>
            </div>
        <?php } ?>

        <div class="panel-body">
            <div class="bootstrap-table">
                <?php if (isset($this->newButton)) { ?>
                    <div class="panel-footer text-left">
                        <a style="margin-left: 10px" <?php if (isset($this->newButton['id'])) echo 'id=' . $this->newButton['id'] ?> class="btn btn-lg btn-primary" href='<?php echo $this->newButton['href'] ?>'><?php echo $this->newButton['text'] ?></a>
                    </div>

                <?php } ?>
                <table id="demo-table" class="table-striped" data-toolbar="#demo-custom-toolbar" data-sort-name="id" data-sort-order="desc" data-pagination="true" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-click-to-select="false">
                    <thead id="cabecalho">
                    <tr>
                        <?php
                        foreach ($this->tableInformation as $th) {
                            if ($th['index'] == 'checkbox') {
                                ?>
                                <th data-align="center" data-sortable="false" data-checkbox="true"></th><?php } else { ?>
                                <th data-field="<?php echo $th['index'] ?>" data-align="center" data-events="<?php
                                if (isset($th['events'])) {
                                    echo $th['events'];
                                }
                                ?>" data-sortable="true" data-formatter="<?php echo $th['format'] ?>" ><?php echo $th['descricao'] ?></th>
                            <?php
                            }
                        }
                        ?>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $JQuery(function() {
        $JQuery('[name="refresh"]').click(function() {
            var aux = window.location.pathname;
            $('#demo-table').bootstrapTable('refresh', {url: aux});
        });
    });
    function downloadExportFormatter(value, row) {
        if (value)
        {
            if (value == "Em andamento...") {
                return value;
            }
            else
                return '<a href="<?= BASE_URL; ?>/exportacao/exportar-xls/file/id/' + JSON.stringify(row.id) + '" class="btn-link"  title="Download do arquivo"> ' + value + '</a>';
        }
        return '-';
    }

    function statusRegra(value, row){
        if (value === '1'){
            return '<i class="fa fa-check fa-2x"></i> ';
        } else {
            return '<i class="fa fa-spin fa-spinner fa-pulse fa-2x"></i> ';
        }
    }

    function gridFormatter(value, row){
        if (value)
            return '<a href="<?php echo $this->addIcon[0]['url']; ?>/table/' + row.table_name + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
    }
    function nameFormatter(value, row) {
        if (value)
            return '<a href="<?php echo $this->addIcon[0]['url']; ?>/id/' + row.id + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
    }
    function nameFormatterTxt(value, row) {
        if (value)
            return '<a href="<?php echo $this->addIcon[0]['url']; ?>/txt/' + JSON.stringify(row.id) + '" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
    }
    function newsFormatter(value, row) {
        if (value)
            console.log(row.href);
        return '<a href="' + row.href + '" target="_blank" class="btn-link" title="<?php echo $this->addIcon[0]['title']; ?>"> ' + value + '</a>';
        return '-';
    }
    function operateFormatter(value, row, index) {
        return [
            <?php foreach ($this->addIcon as $item) {
                        if(isset($item['onClick'])){?>
            '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" onclick="<?php echo $item['onClick']?>" title="<?php echo $item['title']; ?>">',
            <?php } else { ?>
            '<a class="<?php echo $item['classHref']; ?>" href="javascript:void(0)" title="<?php echo $item['title']; ?>">',
            <?php } ?>
            '<i class="<?php echo $item['classButton']; ?>"></i>',
            '</a>&nbsp;&nbsp;&nbsp;',
            <?php } ?>
        ].join('');
    }

    window.operateEvents = {
        <?php
        foreach ($this->addIcon as $item) {
            if ($item['classHref'] == 'remove') {
                ?>
        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            <?php if(!isset($item['sem_confirm'])){?>
            if (confirm('Deseja deletar este registro?')){
                window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
//                    console.log(value, row, index);
            }
            <?php } ?>
        },
        <?php } else if ($item['classHref'] == 'grid') { ?>
        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id) + '/tabela/' + JSON.stringify(row.tabela_alvo));
//                    console.log(value, row, index);
        },
        <?php } else if ($item['classHref'] == 'basedados') { ?>
        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            window.location.assign("<?php echo $item['url']; ?>/table/" + JSON.stringify(row.table_name));
//                    console.log(value, row, index);
        },
        <?php } else if ($item['classHref'] == 'reg') { ?>
        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            window.location.assign("<?php echo $item['url']; ?>/tipo/" + JSON.stringify(row.reg));
//                    console.log(value, row, index);
        },
        <?php } else { ?>
        'click .<?php echo $item['classHref']; ?>': function(e, value, row, index) {
            window.location.assign("<?php echo $item['url']; ?>/id/" + JSON.stringify(row.id));
//                    console.log(value, row, index);
        },
        <?php } ?>
        <?php } $id_processo = $this->session()->offsetGet('processo'); ?>
    };</script>

<script type="text/javascript">
    <?php if ($id_processo >= 1) { ?>
    function mostrarModals(){
        var processo;
        var etapa;
        $JQuery(function () {
            $.ajax({
                type: 'POST',
                url: '<?php echo BASE_URL ?>/main/processo-apuracao/etapa-processo',
                data: {'id': <?php echo $id_processo ?>},
                dataType: 'JSON',
                async: false,
                success: function (d) {
                    etapas(d);
                }
            });
            $('#dialog-new').modal('toggle');
            $JQuery("#titulo-modal").replaceWith('<h4 class="modal-title" id="titulo-modal"><b>Etapas do processo:</b> <?= $modal ?></h4>');
        });
    };
    <?php } ?>
    function etapas(d) {
        $JQuery('#importacao').removeClass();
        $JQuery('#importacao').addClass(d.importacao.classe);
        $JQuery('#importaxml').removeClass();
        $JQuery('#importaxml').addClass(d.nfe.classe);
        if (d.nfe.block !== '') {
            $JQuery('#importaxml').css('pointer-events', 'none');
        } else {
            $JQuery('#importaxml').css('pointer-events', '');
        }
        $JQuery('#importacte').removeClass();
        $JQuery('#importacte').addClass(d.cte.classe);
        if (d.cte.block !== '') {
            $JQuery('#importacte').css('pointer-events', '');
            $JQuery('#importacte').css('pointer-events', 'none');
        } else {
            $JQuery('#importacte').css('pointer-events', '');
        }
        $JQuery('#conciliacao').removeClass();
        $JQuery('#conciliacao').addClass(d.conciliacao.classe);
        if (d.conciliacao.block !== '') {
            $JQuery('#conciliacao').css('pointer-events', 'none');
        } else {
            $JQuery('#concilaicao').css('pointer-events', '');
        }
        $JQuery('#regras').removeClass();
        $JQuery('#regras').addClass(d.regras.classe);
        if (d.regras.block !== '') {
            $JQuery('#regras').css('pointer-events', 'none');
        } else {
            $JQuery('#regras').css('pointer-events', '');
        }
        $JQuery('#apuracaosped').removeClass();
        $JQuery('#apuracaosped').addClass(d.apuracao.classe);
        if (d.apuracao.block !== '') {
            $JQuery('#apuracao').css('pointer-events', 'none');
        } else {
            $JQuery('#apuracao').css('pointer-events', '');
        }
        $JQuery('#exportar').removeClass();
        $JQuery('#exportar').addClass(d.exportacao.classe);
        if (d.exportacao.block !== '') {
            $JQuery('#exportar').css('pointer-events', 'none');
        } else {
            $JQuery('#exportar').css('pointer-events', '');
        }
    }

    function importar() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importar/save/id/<?php echo $id_processo ?>');
    };
    function importaxml() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarxml/index/id/<?php echo $id_processo ?>');
    };
    function importacte() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarcte/index/id/<?php echo $id_processo ?>');
    };
    function apuracao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/apuracao/index/id/<?php echo $id_processo ?>');
    };
    function encerrar() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/encerramento/id/<?php echo $id_processo ?>');
        }
    };
    function exportar() {
        window.location.assign('<?= BASE_URL; ?>' + '/exportacao/exportar-xls/export/id/<?php echo $id_processo ?>');
    };
    function regras() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/regrasprocesso/index/id/<?php echo $id_processo ?>');
    };
    function remover() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/delete/id/<?php echo $id_processo ?>');
        }
    };
    function conciliacao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/conciliacao/index/id/<?php echo $id_processo ?>');
    };
</script>
