<style>
    .breadcrumb{
        font-size: 20px;
        color:#000;
    }
    .active-floatlabel{
        padding-top: 13px !important;
    }
</style>
<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else { ?>
                    <li><strong><?php echo $breadcrumb['text']; ?></strong></li>
                <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<!-- ##### HEAD DA PAGINA #####-->
<link href="/css/jquery.treemenu.css" rel="stylesheet" type="text/css"/>
<!-- ##### FIM DA HEAD #####-->

<div id="page-content">
    <div class="panel">
        <?php if (isset($this->help)) { ?>
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->help ?></h3>
            </div>
        <?php } ?>
        <div id="page-content">
            <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
            <!--===================================================-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">

            <?php
            echo $this->form()->openTag($this->form);
            $messageError = $this->form->getMessages();
            ?>
            <div class="col-md-12 col-lg-12 eq-box-lg" style="background-color: white; margin-top:-15px; padding-bottom: 30px;">
                <div class="row">
                    <?php
                    $classError = 'has-error has-feedback';
                    $errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
                    $cont = 0;
                    foreach ($this->partialElements as $chave => $element) {
                        if (isset($element['id_div'])) {
                            $idDiv = 'id="' . $element['id_div'] . '"';
                        } else {
                            $idDiv = '';
                        }
                        if (isset($element['htmlElement'])) {
                            $html = '<div>' . $element['htmlElement'] . '</div>';
                        } else {
                            $html = '';
                        }
                        if (!isset($element['grupo'])) {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                            ?>
                            <?php if ($cont == 0) { ?>
                                <div class="col-sm-<?php echo $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                    <div <?php echo $idDiv ?> class="input-group mar-btm<?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                        <?php
                                        if (!isset($element['none'])) {
                                            if (isset($element['label']) && !isset($element['icon'])) {
                                                echo $element['label'];
                                            } else {
                                                if (isset($element['icon']) && isset($element['nome'])) {
                                                    ?>
                                                    <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                <i class="<?php echo $element['icon']; ?>" ></i>
                                            </span>
                                                <?php
                                                }
                                            }
                                        }
                                        ?>
                                        <?php
                                        if (isset($element['calendario'])) {
                                            ?>
                                            <div id="demo-dp-txtinput">
                                                <?php echo $element['input'] ?>
                                            </div>
                                        <?php
                                        } else if (!isset($element['type'])) {
                                            echo $element['input'];
                                            if (isset($messageError[$element['name']])) {
                                                $messageErrorExib = array_pop($messageError[$element['name']]);
                                                echo $errorIcon;
                                                echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                            }
                                        } else {
                                            ?>
                                            <br>
                                            <span class="btn btn-default btn-file">
                                        <?php
                                        echo $element['label'];
                                        echo $element['input'];
                                        ?>
                                    </span>
                                        <?php } ?>
                                        <span class="info clearfix">
                                    <?php
                                    if (isset($element['information']))
                                        echo $element['information'];
                                    else if (isset($element['information2']))
                                        echo $element['information'];
                                    ?>
                                </span>
                                    </div>
                                </div>
                                <?php
                                $cont = 1;
                            } else {
                                ?>
                                <div class="col-sm-<?php echo $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                    <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                        <?php
                                        if (!isset($element['none'])) {
                                            if (isset($element['label']) && !isset($element['icon'])) {
                                                echo $element['label'];
                                            } else {
                                                if (isset($element['icon']) && isset($element['nome'])) {
                                                    ?>
                                                    <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                                <i class="<?php echo $element['icon']; ?>" ></i>
                                            </span>
                                                <?php
                                                }
                                            }
                                        }
                                        ?>
                                        <?php
                                        if (isset($element['calendario'])) {
                                            ?>
                                            <div id="demo-dp-txtinput">
                                                <?php echo $element['input'] ?>
                                            </div>
                                        <?php
                                        } else if (!isset($element['type'])) {
                                            echo $element['input'];
                                            if (isset($messageError[$element['name']])) {
                                                $messageErrorExib = array_pop($messageError[$element['name']]);
                                                echo $errorIcon;
                                                echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                            }
                                        } else {
                                            ?>
                                            <br>
                                            <span class="btn btn-default btn-file">
                                        <?php
                                        echo $element['label'];
                                        echo $element['input'];
                                        ?>
                                    </span>
                                        <?php } ?>
                                        <span class="info clearfix">
                                    <?php
                                    if (isset($element['information']))
                                        echo $element['information'];
                                    else if (isset($element['information2']))
                                        echo $element['information'];
                                    ?>
                                </span>
                                    </div>
                                </div>
                                <?php
                                $cont = 0;
                            }
                        }
                    }
                    if (isset($radio)) {
                        foreach ($radio as $chave => $element) {
                            if (isset($element['id_div'])) {
                                $idDiv = 'id="' . $element['id_div'] . '"';
                            } else {
                                $idDiv = '';
                            }
                        }
                        ?>
                        <div class="col-sm-6">
                            <div <?php echo $idDiv ?> class="form-group">
                                <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                                <div class="radio">
                                    <!-- INLINE CHECKBOXES -->
                                    <!--===================================================-->
                                    <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                        <label class="form-radio form-icon active">
                                            <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id'] . '-' . $chaves; ?>" value="<?php echo $chaves; ?>" type="radio"><?php echo $elements; ?>
                                        </label>
                                        <!--===================================================-->
                                    <?php } ?>
                                    <?php
                                    if (isset($messageError[$element['name']])) {
                                        $messageErrorExib = array_pop($messageError[$element['name']]);
                                        echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    <?php
                    }
                    ?>
                </div>
                <hr>
            </div>
            <div class="row">
                <div class="col-md-12 col-lg-12 eq-box-lg" style="background-color: white; margin-top:-15px; padding-bottom: 30px;">
                    <div class="row">
                        <?php
                        $classError = 'has-error has-feedback';
                        $errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
                        $cont = 0;
                        foreach ($this->partidosElemento as $chave => $element) {
                            if (isset($element['id_div'])) {
                                $idDiv = 'id="' . $element['id_div'] . '"';
                            } else {
                                $idDiv = '';
                            }
                            if (isset($element['htmlElement'])) {
                                $html = '<div>' . $element['htmlElement'] . '</div>';
                            } else {
                                $html = '';
                            }
                            if (!isset($element['grupo'])) {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                                ?>
                                <?php if ($cont == 0) { ?>
                                    <div class="col-sm-<?php echo $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                        <div <?php echo $idDiv ?> class="input-group mar-btm<?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                            <?php
                                            if (!isset($element['none'])) {
                                                if (isset($element['label']) && !isset($element['icon'])) {
                                                    echo $element['label'];
                                                } else {
                                                    if (isset($element['icon']) && isset($element['nome'])) {
                                                        ?>
                                                        <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                        </span>
                                                    <?php
                                                    }
                                                }
                                            }
                                            ?>
                                            <?php
                                            if (isset($element['calendario'])) {
                                                ?>
                                                <div id="demo-dp-txtinput">
                                                    <?php echo $element['input'] ?>
                                                </div>
                                            <?php
                                            } else if (!isset($element['type'])) {
                                                echo $element['input'];
                                                if (isset($messageError[$element['name']])) {
                                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                                    echo $errorIcon;
                                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                }
                                            } else {
                                                ?>
                                                <br>
                                                <span class="btn btn-default btn-file">
                                    <?php
                                    echo $element['label'];
                                    echo $element['input'];
                                    ?>
                                </span>
                                            <?php } ?>
                                            <span class="info clearfix">
                                <?php
                                if (isset($element['information']))
                                    echo $element['information'];
                                else if (isset($element['information2']))
                                    echo $element['information'];
                                ?>
                            </span>
                                        </div>
                                    </div>
                                    <?php
                                    $cont = 1;
                                } else {
                                    ?>
                                    <div class="col-sm-<?php echo $this->colunas ?>" style="margin-top: 15px; max-height: 45px; margin-bottom: -15px;">
                                        <div <?php echo $idDiv ?> class="input-group mar-btm <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                            <?php
                                            if (!isset($element['none'])) {
                                                if (isset($element['label']) && !isset($element['icon'])) {
                                                    echo $element['label'];
                                                } else {
                                                    if (isset($element['icon']) && isset($element['nome'])) {
                                                        ?>
                                                        <span class="input-group-addon" title="<?php echo $element['nome'] ?>">
                                            <i class="<?php echo $element['icon']; ?>" ></i>
                                        </span>
                                                    <?php
                                                    }
                                                }
                                            }
                                            ?>
                                            <?php
                                            if (isset($element['calendario'])) {
                                                ?>
                                                <div id="demo-dp-txtinput">
                                                    <?php echo $element['input'] ?>
                                                </div>
                                            <?php
                                            } else if (!isset($element['type'])) {
                                                echo $element['input'];
                                                if (isset($messageError[$element['name']])) {
                                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                                    echo $errorIcon;
                                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                                }
                                            } else {
                                                ?>
                                                <br>
                                                <span class="btn btn-default btn-file">
                                    <?php
                                    echo $element['label'];
                                    echo $element['input'];
                                    ?>
                                </span>
                                            <?php } ?>
                                            <span class="info clearfix">
                                <?php
                                if (isset($element['information']))
                                    echo $element['information'];
                                else if (isset($element['information2']))
                                    echo $element['information'];
                                ?>
                            </span>
                                        </div>
                                    </div>
                                    <?php
                                    $cont = 0;
                                }
                            }
                        }
                        if (isset($radio)) {
                            foreach ($radio as $chave => $element) {
                                if (isset($element['id_div'])) {
                                    $idDiv = 'id="' . $element['id_div'] . '"';
                                } else {
                                    $idDiv = '';
                                }
                            }
                            ?>
                            <div class="col-sm-6">
                                <div <?php echo $idDiv ?> class="form-group">
                                    <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                                    <div class="radio">
                                        <!-- INLINE CHECKBOXES -->
                                        <!--===================================================-->
                                        <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                            <label class="form-radio form-icon active">
                                                <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id'] . '-' . $chaves; ?>" value="<?php echo $chaves; ?>" type="radio"><?php echo $elements; ?>
                                            </label>
                                            <!--===================================================-->
                                        <?php } ?>
                                        <?php
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        <?php
                        }
                        ?>
                    </div>
                    <div class="text-right" >
                        <button type="submit" class="btn btn-info" id="submitbutton" style="margin-top:40px;">Salvar</button>
                        <button type="button" class="btn btn-danger" id="cancelar" style="margin-top:40px;">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/js/jquery.treemenu.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL ?>/js/floatlabels.js" type="text/javascript"></script>
<script type="text/javascript">
    $JQuery('input.floatlabel').floatlabel();
    $JQuery(document).ready(function () {
        $JQuery(".tree").treemenu({delay: 100});
    });

</script>
