<style>
    .breadcrumb{
        font-size: 20px;
        color:#000;
    }
    .active-floatlabel{
        padding-top: 13px !important;
    }
</style>
<!-- ##### CRIAÇÃO DOS BREADCRUMBS #####-->
<?php
if (isset($this->breadcrumbs))
    if ($this->breadcrumbs) {
        $keys = array_keys($this->breadcrumbs);
        $endKey = end($keys);
        ?>
        <ol class="breadcrumb">
            <li>Você está aqui: </li>
            <?php
            foreach ($this->breadcrumbs as $chave => $breadcrumb) {
                if ($breadcrumb['url'] == '#')
                    $urlBreadcrumb = '#';
                else
                    $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
                ?>
                <?php if ($endKey != $chave) { ?>
                    <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                <?php } else { ?>
                    <li><strong><?php echo $breadcrumb['text']; ?></strong></li>
                <?php
                }
            }
            ?>
        </ol>
    <?php } ?>
<!-- ##### FIM DOS BREADCRUMBS #####-->

<!-- ##### HEAD DA PAGINA #####-->
<link href="/css/jquery.treemenu.css" rel="stylesheet" type="text/css"/>
<!-- ##### FIM DA HEAD #####-->

<div id="page-content">
    <div class="panel">
        <?php if (isset($this->help)) { ?>
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->help ?></h3>
            </div>
        <?php } ?>
        <div id="page-content">
            <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
            <!--===================================================-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">
            <div class="row">
                <div class="col-md-12 col-lg-12">
                    <!--Default Accordion-->
                    <!--===================================================-->
                    <div class="panel">
                        <?php if(isset($this->sanfona[1]['n5'])) {
                            $flag = 0;
                            foreach ($this->sanfona as $dado => $item) {
                                if ($item['n2'] == 0 || $flag == 84) { ?>
                                    <ul class="tree">
                                    <li>
                                    <a href="#" style="background-color: #cfd3f2"><?php echo $item['nome_conta_contabil']; ?></a>
                                    <?php
                                    $flag = 0;
                                } else if ($item['n3'] == 0 || $flag == 42) { ?>
                                    <ul>
                                    <li>
                                    <a href="#"><?php echo $item['nome_conta_contabil']; ?></a>
                                    <?php
                                    $flag = 0;
                                } else if ($item['n4'] == 0 || $flag == 12) { ?>
                                    <ul>
                                    <li>
                                    <a href="#"><?php echo $item['nome_conta_contabil']; ?></a>
                                    <?php
                                    if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n4'] == 0) {
                                        $flag = 12; ?>
                                        </li>
                                        </ul>
                                    <?php
                                    }
                                    $flag = 0;
                                } else if ($item['n5'] == 0 || $flag == 6) { ?>
                                    <ul>
                                        <li>
                                            <a href="#"><?php echo $item['nome_conta_contabil']; ?></a>
                                    <?php
                                    if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n5'] == 0) {
                                        $flag = 6; ?>
                                        </li>
                                        </ul>
                                    <?php
                                    }
                                    if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n4'] == 0) {
                                        $flag = 12; ?>
                                        </li>
                                        </ul>
                                        </li>
                                        </ul>
                                    <?php
                                    }
                                    if(isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n2'] == 0) {
                                        $flag = 84; ?>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                    <?php
                                    }
                                    $flag = 0;
                                } else if ($item['n5'] != 0) { ?>
                                    <ul>
                                        <li>
                                            <a href="#"><?php echo $item['nome_conta_contabil']; ?></a>
                                        </li>
                                    </ul>
                                    <?php
                                    if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n2'] == 0) {
                                        $flag = 84; ?>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                    <?php
                                    } else if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n3'] == 0) {
                                        $flag = 42; ?>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                        <?php
                                    } else if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n4'] == 0) {
                                        $flag = 12; ?>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                        <?php
                                    } else if (isset($this->sanfona[$dado + 1]['conta_contabil']) && $this->sanfona[$dado + 1]['n5'] == 0) {
                                        $flag = 6; ?>
                                            </li>
                                        </ul>
                                        <?php
                                    }
                                } else { ?>
                                        </li>
                                    </ul>
                                        </li>
                                    </ul>
                                        </li>
                                    </ul>
                                        </li>
                                    </ul>
                                    <?php
                                    $flag = 0;
                                }
                            }
                        } else {
                            $flag = 0; ?>
                            <ul class="tree">
                                <li>
                                    <form id="planos_conta" name="planos_conta" method="POST" action="">
                                        <input id="nome_conta_financeiro" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Nome Conta Financeiro" data-class="red-label" placeholder="Nome Conta Financeiro" name="n1" style="margin-top: -28px; margin-left: 8px; width: 30%; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                    </form>
                                </li>
                            </ul>
                            <?php foreach ($this->sanfona as $dado => $item) {
                                if ($item['n2'] == 0 || $flag == 84) { ?>
                                    <ul class="tree">
                                        <li>
                                            <a href="#" style="font-weight: bold"><?php echo $item['n1'].'.'.$item['n2'].'.'.$item['n3'].' - '.$item['nome_conta_financeiro']; ?></a><a href="<?= BASE_URL.'/planosconta/planofinanceiro/delete/nome/'.$item['nome_conta_financeiro'] ?>" class="remove" title="Excluir" style="margin-left: 2%"><i class="glyphicon glyphicon-trash"></i></a>
                                    <ul>
                                        <li>
                                            <form id="planos_conta" name="planos_conta" method="POST" action="">
                                                <input id="nome_conta_financeiro" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Nome Conta Financeiro" data-class="red-label" placeholder="Nome Conta Financeiro" name="<?= 'n2_'.$item['n1']?>" style="margin-top: -28px; margin-left: 8px; width: 30%; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                            </form>
                                        </li>
                                    </ul>
                                    <?php
                                    $flag = 0;
                                } else if ($item['n3'] == 0 || $flag == 42) { ?>
                                    <ul>
                                        <li>
                                            <a href="#"><?php echo $item['n1'].'.'.$item['n2'].'.'.$item['n3'].' - '.$item['nome_conta_financeiro']; ?></a><a href="<?= BASE_URL.'/planosconta/planofinanceiro/delete/nome/'.$item['nome_conta_financeiro'] ?>" class="remove" title="Excluir" style="margin-left: 2%"><i class="glyphicon glyphicon-trash"></i></a>
                                    <?php
                                    $flag = 0;
                                } else if ($item['n3'] != 0) { ?>
                                    <ul>
                                        <li>
                                            <a href="#"><?php echo $item['n1'].'.'.$item['n2'].'.'.$item['n3'].' - '.$item['nome_conta_financeiro']; ?></a><a href="<?= BASE_URL.'/planosconta/planofinanceiro/delete/nome/'.$item['nome_conta_financeiro'] ?>" class="remove" title="Excluir" style="margin-left: 2%"><i class="glyphicon glyphicon-trash"></i></a>
                                        </li>
                                    </ul>
                                    <?php
                                    $flag = 0;
                                    if (isset($this->sanfona[$dado + 1]['conta_financeiro']) && $this->sanfona[$dado + 1]['n3'] == 0 && $this->sanfona[$dado + 1]['n2'] != 0) {
                                        $flag = 42; ?>
                                        <ul>
                                            <li>
                                                <form id="planos_conta" name="planos_conta" method="POST" action="">
                                                    <input id="nome_conta_financeiro" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Nome Conta Financeiro" data-class="red-label" placeholder="Nome Conta Financeiro" name="<?= 'n3_'.$item['n1'].'_'.$item['n2']?>" style="margin-top: -28px; margin-left: 8px; width: 30%; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                                </form>
                                            </li>
                                        </ul>
                                        </li>
                                        </ul>
                                    <?php
                                    } else if (isset($this->sanfona[$dado + 1]['conta_financeiro']) && $this->sanfona[$dado + 1]['n3'] == 0 && $this->sanfona[$dado + 1]['n2'] == 0) {
                                        $flag = 84; ?>
                                        <ul>
                                            <li>
                                                <form id="planos_conta" name="planos_conta" method="POST" action="">
                                                    <input id="nome_conta_financeiro" class="new-input form-control demo-oi-errinput floatlabel" type="text" value="" data-label="Nome Conta Financeiro" data-class="red-label" placeholder="Nome Conta Financeiro" name="<?= 'n3_'.$item['n1'].'_'.$item['n2']?>" style="margin-top: -28px; margin-left: 8px; width: 30%; transition: all 0.1s ease-in-out 0s;" data-original-title="" title="">
                                                </form>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                            </li>
                                        </ul>
                                        <?php
                                    }
                                } else { ?>
                                        </li>
                                    </ul>
                                        </li>
                                    </ul>
                                    <?php
                                    $flag = 0;
                                }
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/js/jquery.treemenu.js" type="text/javascript"></script>
<script src="<?php echo BASE_URL ?>/js/floatlabels.js" type="text/javascript"></script>
<script type="text/javascript">
    $JQuery('input.floatlabel').floatlabel();
    $JQuery(document).ready(function () {
        $JQuery(".tree").treemenu({delay: 100});
    });

</script>
