<style>
    .breadcrumb{
        font-size: 20px;
    }
</style>

<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if ($this->breadcrumbs) {
    $keys = array_keys($this->breadcrumbs);
    $endKey = end($keys);
    ?>
    <ol class="breadcrumb">
        <li>Você está aqui: </li>
        <?php
        foreach ($this->breadcrumbs as $chave => $breadcrumb) {
            if ($breadcrumb['url'] == '#')
                $urlBreadcrumb = '#';
            else
                $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
            ?>
            <?php if ($endKey != $chave) { ?>
                <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } else { ?>
                <li class="active"><?php echo $breadcrumb['text']; ?></li>
                <?php
            }
        }
        ?>

    </ol>

<?php } ?>

<div id="page-content">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->help; ?></h3>
        </div>
        <div class="panel-body">
            <!--GAMBIARRA PARA FUNCIONAR O SELECT COM BUSCA-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">
            <!--=============== FIM GAMBIARRA ============= -->
            <?php
            echo $this->form()->openTag($this->form);
            $messageError = $this->form->getMessages();
            ?>
            <div id="append" class="panel-body">
                <?php
                $cont = 0;
                                foreach ($this->partialElements as $chave => $element) {

                    if (isset($element['id_div'])) {
                        $idDiv = 'id="' . $element['id_div'] . '"';
                    } else {
                        $idDiv = '';
                    }
                    if (isset($element['htmlElement'])) {
                        $html = '<div>' . $element['htmlElement'] . '</div>';
                    } else {
                        $html = '';
                    }
                    if ($element['name'] != 'perfis') {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                        ?>
                        <?php if ($cont == 0) { ?>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div <?php echo $idDiv ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                        <?php
                                        if (isset($element['label'])) {
                                            echo $element['label'];
                                        }
                                        if(isset($element['calendario'])){ ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                       <?php }
                                        else if (!isset($element['type'])) {
                                            echo $element['input'];
                                            if (isset($messageError[$element['name']])) {
                                                $messageErrorExib = array_pop($messageError[$element['name']]);
                                                echo $errorIcon;
                                                echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                            }
                                        } else {
                                            ?>
                                            <br>	
                                            <span class="btn btn-default btn-file"> 
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                        <?php } ?>
                                        <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>
                                    </div>
                                </div>
                                <?php
                                $cont = 1;
                            } else {
                                ?>
                                <div class="col-sm-6">
                                    <div <?php echo $idDiv ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                        <?php
                                        if (isset($element['label'])) {
                                            echo $element['label'];
                                        }
                                        if(isset($element['calendario'])){ ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                       <?php }
                                        else if (!isset($element['type'])) {
                                            echo $element['input'];

                                            if (isset($messageError[$element['name']])) {
                                                $messageErrorExib = array_pop($messageError[$element['name']]);
                                                echo $errorIcon;
                                                echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                            }
                                        } else {
                                            ?>
                                            <br>			
                                            
                                                <span class="btn btn-default btn-file"> 
                                                    <?php
                                                    echo $element['label'];
                                                    echo $element['input'];
                                                    ?>
                                                </span>
                                        <?php } ?>
                                        <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>

                                    </div>
                                    <?php echo $html; ?>
                                </div>
                            </div>
                            <?php
                            $cont = 0;
                        }
                        ?>

                        <?php
                    }
                }
                if (isset($checkbox)) {
                    foreach ($checkbox as $chave => $element) {
                        if (isset($element['id_div'])) {
                            $idDiv = 'id="' . $element['id_div'] . '"';
                        } else {
                            $idDiv = '';
                        }
                        ?>

                        <div <?php echo $idDiv ?> class="form-group">
                            <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                            <div class="checkbox">
                                <!-- INLINE CHECKBOXES -->
                                <!--===================================================-->
                                <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                    <?php if (isset($element['style'])) { ?>
                                        <div>
                                        <?php } ?>
                                        <label id="<?php echo $chaves ?>" class="form-checkbox form-icon active">
                                            <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id']; ?>" value="<?php echo $chaves; ?>" type="checkbox"><?php echo $elements; ?>
                                        </label>
                                        <!--===================================================-->
                                        <?php if (isset($element['style'])) { ?>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                                <?php
                                if (isset($messageError[$element['name']])) {
                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                }
                                ?>
                            </div>
                        </div>
                        <?php
                    }
                }
                ?>
                <div class="panel-footer text-right">
                    <button id="submitbutton" type="submit" class="btn btn-primary">Salvar</button>
                    <?php
                    if (array_key_exists('botao2', $this->form->getElements()))
                        echo $this->formRow($this->form->get('botao2'));
                    if (array_key_exists('cancelar', $this->form->getElements()))
                        echo $this->formButton($this->form->get('cancelar'));
                    ?>
                </div>
                <?php echo $this->form()->closeTag($this->form); ?>
            </div>
        </div>
    </div>


    <script src = "/js/jquery-2.1.1.min.js"></script>