<?php
/*
 * @author Cezar Jr. Souza <cezar08@unochapeco.edu.br>
 *
 * @params array $breadcrumbs, string $titlePage, Zend/Form $form, array $partialElements, string @help
 * @retrun void
 * Template para gerar formulários
 */
?>
<?php
$classError = 'has-error has-feedback';
$errorIcon = '<span class="fa fa-times fa-lg form-control-feedback"></span>';
if ($this->breadcrumbs) {
    $keys = array_keys($this->breadcrumbs);
    $endKey = end($keys);
    ?>
    <ol class="breadcrumb">
        <li>Você está aqui: </li>
        <?php
        foreach ($this->breadcrumbs as $chave => $breadcrumb) {
            if ($breadcrumb['url'] == '#')
                $urlBreadcrumb = '#';
            else
                $urlBreadcrumb = BASE_URL . $breadcrumb['url'];
            ?>
            <?php if ($endKey != $chave) { ?>
                <li><a href="<?php echo $urlBreadcrumb; ?>" title="<?php echo $breadcrumb['title']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php
            } else {
                if (isset($modal) && $modal != '') {
                    ?>
                    <li><a href="#" title="<?= $modal ?>" onclick="mostrarModals();"><?php echo $modal; ?></a></li>
                <?php } ?>
                <li class="active"><strong><?php echo $breadcrumb['text']; ?></strong></li>
            <?php
            }
        }
        ?>

    </ol>

<?php } ?>


<!--===================================================-->
<!-- END OF PAGE TITLE -->
<!-- PERMITE O FUNCIONAMENTO DO DATEPICKER -->
<div id="demo-range-def" style="display: none;"></div>
<div id="demo-range-step" style="display: none;"></div>
<div id="demo-range-ver1" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver2" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver3" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver4" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-ver5" class="demo-range-ver" style="display: none;"></div>
<div id="demo-range-vpips" class="demo-pips demo-range-ver pips" style="display: none;"></div>
<div id="demo-range-drg" style="display: none;"></div>
<div id="demo-range-fxt" style="display: none;"></div>
<div id="demo-range-com" style="display: none;"></div>
<div id="demo-range-hpips" class="demo-pips pips" style="display: none;"></div>
<!-- FIM -->
<!-- PAGE CONTENT -->
<!--===================================================-->
<div id="page-content">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->help; ?></h3>
        </div>
        <div class="panel-body">




            <!-- PAGE CONTENT Gambiarra para funcionar o select com busca-->
            <!--===================================================-->
            <input id="demo-sw-checkstate" type="hidden">
            <input id="demo-sw-checkstate-field"  type="hidden">
            <!--===================================================-->
            <!-- END OF PAGE CONTENT -->



            <!-- BLOCK STYLED FORM FORM  -->
            <!--===================================================-->
            <?php
            echo $this->form()->openTag($this->form);
            $messageError = $this->form->getMessages();
            ?>
            <div id="append" class="panel-body">
                <?php
                $cont = 0;
                if (isset($upperCheckbox)) {
                    foreach ($upperCheckbox as $elementos) {
                        foreach ($elementos as $chave => $element) {
                            if (isset($element['id_div'])) {
                                $idDiv = 'id="' . $element['id_div'] . '"';
                            } else {
                                $idDiv = '';
                            }
                            ?>

                            <div <?php echo $idDiv ?> class="form-group">
                                <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                                <div class="checkbox">
                                    <!-- INLINE CHECKBOXES -->
                                    <!--===================================================-->
                                    <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                        <?php if (isset($element['style'])) { ?>
                                            <div>
                                        <?php } ?>
                                        <label id="<?php echo $chaves ?>" class="form-checkbox form-icon active">
                                            <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id']; ?>" value="<?php echo $chaves; ?>" type="checkbox"><?php echo $elements; ?>
                                        </label>
                                        <!--===================================================-->
                                        <?php if (isset($element['style'])) { ?>
                                            </div>
                                        <?php } ?>
                                    <?php } ?>
                                    <?php
                                    if (isset($messageError[$element['name']])) {
                                        $messageErrorExib = array_pop($messageError[$element['name']]);
                                        echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php
                        }
                    }
                }
                foreach ($this->partialElements as $chave => $element) {

                    if (isset($element['id_div'])) {
                        $idDiv = 'id="' . $element['id_div'] . '"';
                    } else {
                        $idDiv = '';
                    }
                    if (isset($element['htmlElement'])) {
                        $html = '<div>' . $element['htmlElement'] . '</div>';
                    } else {
                        $html = '';
                    }
                    if ($element['name'] != 'perfis') {//Verifica se os elementos são checkbox, para distribuílos em uma linha
                        ?>
                        <?php if ($cont == 0) { ?>
                            <div class="row">
                            <div class="col-sm-3">
                                <div <?php echo $idDiv ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (isset($element['label'])) {
                                        echo $element['label'];
                                    }
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>
                                        <span class="btn btn-default btn-file">
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>
                                </div>
                            </div>
                            <?php
                            $cont = 1;
                        } else if ($cont ==1) {
                            ?>
                            <div class="col-sm-3">
                                <div <?php echo $idDiv ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (isset($element['label'])) {
                                        echo $element['label'];
                                    }
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];

                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>

                                        <span class="btn btn-default btn-file">
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>

                                </div>
                                <?php echo $html; ?>
                            </div>
                            <?php
                            $cont = 2;
                        } else if ($cont == 2) { ?>
                            <div class="col-sm-3">
                                <div <?php echo $idDiv ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (isset($element['label'])) {
                                        echo $element['label'];
                                    }
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];
                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>
                                        <span class="btn btn-default btn-file">
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>
                                </div>
                            </div>
                            <?php
                            $cont = 3;
                        } else {
                            ?>
                            <div class="col-sm-3">
                                <div <?php echo $idDiv ?> class="form-group <?php if (isset($messageError[$element['name']])) echo $classError; ?>">
                                    <?php
                                    if (isset($element['label'])) {
                                        echo $element['label'];
                                    }
                                    if (isset($element['calendario'])) {
                                        ?>
                                        <div id="demo-dp-txtinput">
                                            <?php echo $element['input'] ?>
                                        </div>
                                    <?php
                                    } else if (!isset($element['type'])) {
                                        echo $element['input'];

                                        if (isset($messageError[$element['name']])) {
                                            $messageErrorExib = array_pop($messageError[$element['name']]);
                                            echo $errorIcon;
                                            echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                        }
                                    } else {
                                        ?>
                                        <br>

                                        <span class="btn btn-default btn-file">
                                                <?php
                                                echo $element['label'];
                                                echo $element['input'];
                                                ?>
                                            </span>
                                    <?php } ?>
                                    <span class="info clearfix">
                                            <?php
                                            if (isset($element['information']))
                                                echo $element['information'];
                                            else if (isset($element['information2']))
                                                echo $element['information'];
                                            ?>
                                        </span>

                                </div>
                                <?php echo $html; ?>
                            </div>
                            </div>
                            <?php
                            $cont = 0; ?>
                        <?php
                        }
                    }
                }

                if ($cont == 1)
                    echo '</div>';
                echo '</div>';
                if (isset($checkbox)) {
                    foreach ($checkbox as $chave => $element) {
                        if (isset($element['id_div'])) {
                            $idDiv = 'id="' . $element['id_div'] . '"';
                        } else {
                            $idDiv = '';
                        }
                        ?>

                        <div <?php echo $idDiv ?> class="form-group">
                            <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                            <div class="checkbox">
                                <!-- INLINE CHECKBOXES -->
                                <!--===================================================-->
                                <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                    <?php if (isset($element['style'])) { ?>
                                        <div>
                                    <?php } ?>
                                    <label id="<?php echo $chaves ?>" class="form-checkbox form-icon active">
                                        <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id']; ?>" value="<?php echo $chaves; ?>" type="checkbox"><?php echo $elements; ?>
                                    </label>
                                    <!--===================================================-->
                                    <?php if (isset($element['style'])) { ?>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                                <?php
                                if (isset($messageError[$element['name']])) {
                                    $messageErrorExib = array_pop($messageError[$element['name']]);
                                    echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                                }
                                ?>
                            </div>
                        </div>
                    <?php
                    }
                }
                if (isset($radio)) {
                    foreach ($radio as $chave => $element) {
                        if (isset($element['id_div'])) {
                            $idDiv = 'id="' . $element['id_div'] . '"';
                        } else {
                            $idDiv = '';
                        }
                    }
                    ?>
                    <div <?php echo $idDiv ?> class="form-group">
                        <label class="control-label" for="demo-hor-inputemail"><?php echo $element['label']; ?></label>
                        <div class="radio">
                            <!-- INLINE CHECKBOXES -->
                            <!--===================================================-->
                            <?php foreach ($element['values'] as $chaves => $elements) { ?>
                                <label class="form-radio form-icon active">
                                    <input  name="<?php echo $element['name']; ?>" id="<?php echo $element['id']; ?>" value="<?php echo $chaves; ?>" type="radio"><?php echo $elements; ?>
                                </label>
                                <!--===================================================-->
                            <?php } ?>
                            <?php
                            if (isset($messageError[$element['name']])) {
                                $messageErrorExib = array_pop($messageError[$element['name']]);
                                echo '<label for="demo-oi-errinput" class="control-label">' . $messageErrorExib . '</label>';
                            }
                            ?>
                        </div>
                    </div>
                <?php }
                ?>


                <?php if (!isset($this->ocultarSubmit)) { ?>
                    <div class="panel-footer text-right">
                        <?php
                        if (array_key_exists('adicionar', $this->form->getElements()))
                            echo $this->formRow($this->form->get('adicionar'));
                        if (array_key_exists('cancelar2', $this->form->getElements()))
                            echo $this->formRow($this->form->get('cancelar2'));
                        ?>
                        <?php $submitbutton = isset($this->btnSubmit) ? "$this->btnSubmit" : "Salvar" ?>
                        <button id="submitbutton" type="submit" class="btn btn-primary"><?= $submitbutton; ?></button>
                        <?php
                        if (array_key_exists('botao2', $this->form->getElements()))
                            echo $this->formRow($this->form->get('botao2'));
                        if (array_key_exists('cancelar', $this->form->getElements()))
                            echo $this->formButton($this->form->get('cancelar'));
                        ?>
                    </div>
                    <?php if (isset($this->extraButtons)) { ?>
                        <div class="panel-footer text-left">
                            <?php
                            if (array_key_exists('exportarpva', $this->form->getElements())) {
                                echo $this->formButton($this->form->get('exportarpva'));
                            }
                            if (array_key_exists('exportarnfe', $this->form->getElements())) {
                                echo $this->formButton($this->form->get('exportarnfe'));
                            }
                            ?>
                        </div>
                    <?php } ?>

                <?php } ?>
                <?php echo $this->form()->closeTag($this->form); ?>
                <!--===================================================-->
                <!-- END OF BLOCK STYLED FORM FORM  -->
            </div>
        </div>
    </div>
    <!-- MAIN PLUGIN -->
    <!-- ================================================= -->


    <!-- jQuery Version 2.1.1 -->
    <script src="/js/jquery-2.1.1.min.js"></script>


    <!-- Admin Core -->
</div> <script src="/js/nifty.min.js"></script>
<script src="/js/demo/form-wizard.js"></script>
<?php if (!empty($messageError)) { ?>
    <script>
        $.niftyNoty({
            type: 'danger',
            icon: 'fa fa-bolt fa-2x',
            container: 'page',
            title: 'Foram encontrados problemas no formulário!',
            message: 'Verifique abaixo os campos com avisos, corrija-os e tente novamente.'
        });
    </script>
<?php } $id_processo = $this->session()->offsetGet('processo'); ?>

<script type="text/javascript">
    <?php if ($id_processo >= 1) { ?>
    function mostrarModals() {
        var processo;
        var etapa;
        $JQuery(function () {
            $.ajax({
                type: 'POST',
                url: '<?php echo BASE_URL ?>/main/processo-apuracao/etapa-processo',
                data: {'id': <?php echo $id_processo ?>},
                dataType: 'JSON',
                async: false,
                success: function (d) {
                    etapas(d);
                }
            });
            $('#dialog-new').modal('toggle');
            $JQuery("#titulo-modal").replaceWith('<h4 class="modal-title" id="titulo-modal"><b>Etapas do processo:</b> <?= $modal ?></h4>');
        });
    }
    ;
    <?php } ?>
    function etapas(d) {
        $JQuery('#importacao').removeClass();
        $JQuery('#importacao').addClass(d.importacao.classe);
        $JQuery('#importaxml').removeClass();
        $JQuery('#importaxml').addClass(d.nfe.classe);
        if (d.nfe.block !== '') {
            $JQuery('#importaxml').css('pointer-events', 'none');
        } else {
            $JQuery('#importaxml').css('pointer-events', '');
        }
        $JQuery('#importacte').removeClass();
        $JQuery('#importacte').addClass(d.cte.classe);
        if (d.cte.block !== '') {
            $JQuery('#importacte').css('pointer-events', '');
            $JQuery('#importacte').css('pointer-events', 'none');
        } else {
            $JQuery('#importacte').css('pointer-events', '');
        }
        $JQuery('#conciliacao').removeClass();
        $JQuery('#conciliacao').addClass(d.conciliacao.classe);
        if (d.conciliacao.block !== '') {
            $JQuery('#conciliacao').css('pointer-events', 'none');
        } else {
            $JQuery('#concilaicao').css('pointer-events', '');
        }
        $JQuery('#regras').removeClass();
        $JQuery('#regras').addClass(d.regras.classe);
        if (d.regras.block !== '') {
            $JQuery('#regras').css('pointer-events', 'none');
        } else {
            $JQuery('#regras').css('pointer-events', '');
        }
        $JQuery('#apuracaosped').removeClass();
        $JQuery('#apuracaosped').addClass(d.apuracao.classe);
        if (d.apuracao.block !== '') {
            $JQuery('#apuracao').css('pointer-events', 'none');
        } else {
            $JQuery('#apuracao').css('pointer-events', '');
        }
        $JQuery('#exportar').removeClass();
        $JQuery('#exportar').addClass(d.exportacao.classe);
        if (d.exportacao.block !== '') {
            $JQuery('#exportar').css('pointer-events', 'none');
        } else {
            $JQuery('#exportar').css('pointer-events', '');
        }
    }

    function importar() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importar/save/id/<?php echo $id_processo ?>');
    }
    ;
    function importaxml() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarxml/index/id/<?php echo $id_processo ?>');
    }
    ;
    function importacte() {
        window.location.assign('<?= BASE_URL; ?>' + '/importacao/importarcte/index/id/<?php echo $id_processo ?>');
    }
    ;
    function apuracao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/apuracao/index/id/<?php echo $id_processo ?>');
    }
    ;
    function encerrar() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/encerramento/id/<?php echo $id_processo ?>');
        }
    }
    ;
    function exportar() {
        window.location.assign('<?= BASE_URL; ?>' + '/exportacao/exportar-xls/export/id/<?php echo $id_processo ?>');
    }
    ;
    function regras() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/regrasprocesso/index/id/<?php echo $id_processo ?>');
    }
    ;
    function remover() {
        if (confirm('Deseja deletar este processo e todas as suas informações?') === true) {
            window.location.assign('<?= BASE_URL; ?>' + '/main/processo-apuracao/delete/id/<?php echo $id_processo ?>');
        }
    }
    ;
    function conciliacao() {
        window.location.assign('<?= BASE_URL; ?>' + '/main/conciliacao/index/id/<?php echo $id_processo ?>');
    }
    ;
</script>
